[assembly: InternalsVisibleTo("Vorcyc.Mathematics.Extensions.FFTW")]
[assembly: InternalsVisibleTo("Vorcyc.SignalStudio.Framework")]
[assembly: InternalsVisibleTo("Vorcyc.SignalStudio.Shell")]
[assembly: InternalsVisibleTo("Vorcyc.SignalStudio.DataVisualization")]
[assembly: InternalsVisibleTo("Vorcyc.SignalStudio")]
[assembly: InternalsVisibleTo("DSP_module_test")]
