#!/usr/bin/env python3
"""High-quality CN->EN for Signal Processing wiki lines."""
from __future__ import annotations

import importlib.util
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "tools" / "generate_sp_exact.py"
_spec = importlib.util.spec_from_file_location("gen", GEN)
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)

# Multi-char phrases only (>=2 Chinese chars), longest first
PHRASES: list[tuple[str, str]] = [
    ("  - 返回值:", "  - Returns:"),
    ("  - 参数:", "  - Parameters:"),
    ("  - 异常:", "  - Exceptions:"),
    ("  - 枚举成员:", "  - Enum members:"),
    ("  - 使用 FFT 对 `signal` 和 `kernel` 进行快速卷积。", "  - Uses FFT for fast convolution of `signal` and `kernel`."),
    ("  - 使用 FFT 对 `signal` 和 `kernel` 进行快速互相关。", "  - Uses FFT for fast cross-correlation of `signal` and `kernel`."),
    ("  - 使用多项式除法和 FFT 对 `signal` 和 `kernel` 进行快速反卷积。", "  - Uses polynomial division and FFT for fast deconvolution of `signal` and `kernel`."),
    ("  - 返回值: 卷积结果的 `ComplexDiscreteSignal`。", "  - Returns: `ComplexDiscreteSignal` convolution result."),
    ("  - 返回值: 互相关结果的 `ComplexDiscreteSignal`。", "  - Returns: `ComplexDiscreteSignal` cross-correlation result."),
    ("  - 返回值: 反卷积结果的 `ComplexDiscreteSignal`。", "  - Returns: `ComplexDiscreteSignal` deconvolution result."),
    ("    - `fftSize`: FFT 大小，默认为 0。", "    - `fftSize`: FFT size; default 0."),
    ("  - 获取或设置滤波器的步长因子。", "  - Gets or sets filter step size."),
    ("  - 获取或设置滤波器的泄漏因子。", "  - Gets or sets filter leakage factor."),
    ("  - 构造一个给定阶数的 LmfFilter 实例。", "  - Constructs `LmfFilter` with given order."),
    ("  - 处理输入和期望信号的一个样本，并自适应调整滤波器系数。", "  - Processes one input/desired sample and adaptively updates filter coefficients."),
    ("  - 返回值: 滤波器输出的样本。", "  - Returns: filter output sample."),
    ("        // 定义滤波器阶数、步长因子和泄漏因子", "        // Define filter order, step size, and leakage factor"),
    ("        // 定义输入信号和期望信号", "        // Define input and desired signals"),
    ("        // 处理信号并输出结果", "        // Process signal and print result"),
    ("  - 表示 ADSR 包络的状态。", "  - Represents ADSR envelope state."),
    ("  - 获取当前的 ADSR 状态（攻击、衰减、持续、释放）。", "  - Gets current ADSR state (attack, decay, sustain, release)."),
    ("  - 使用 ADSR 参数（以样本数表示）构造 AdsrBuilder 实例。", "  - Constructs `AdsrBuilder` with ADSR parameters (in sample count)."),
    ("  - 使用 ADSR 参数（以秒为单位）构造 AdsrBuilder 实例。", "  - Constructs `AdsrBuilder` with ADSR parameters (in seconds)."),
    ("  - 生成新的样本。", "  - Generates the next sample."),
    ("  - 返回值: 生成的样本。", "  - Returns: generated sample."),
    ("  - 重置样本生成器。", "  - Resets the sample generator."),
    ("  - 设置信号的采样率。", "  - Sets the signal sample rate."),
    ("  - 返回值: 设置采样率后的 SignalBuilder 实例。", "  - Returns: `SignalBuilder` after setting sample rate."),
    ("获取或设置谱底（beta 系数）", "Gets or sets spectral floor (beta coefficient)"),
    ("获取或设置减法因子的最小阈值（alpha）", "Gets or sets minimum subtraction factor threshold (alpha)"),
    ("获取或设置减法因子的最大阈值（alpha）", "Gets or sets maximum subtraction factor threshold (alpha)"),
    ("获取或设置最小信噪比（以 dB 为单位）", "Gets or sets minimum SNR (dB)"),
    ("获取或设置最大信噪比（以 dB 为单位）", "Gets or sets maximum SNR (dB)"),
    ("获取或设置低通抗混叠 FIR 滤波器的阶数，如果未显式指定滤波器，则会自动创建。默认值为 101",
     "Gets or sets low-pass anti-aliasing FIR filter order; auto-created if not specified. Default 101"),
    ("获取或设置滤波器的步长因子数组", "Gets or sets filter step-size array"),
    ("获取或设置滤波器的归一化因子", "Gets or sets filter normalization factor"),
    ("获取或设置滤波器的遗忘因子", "Gets or sets filter forgetting factor"),
    ("获取或设置滤波器的逆相关矩阵", "Gets or sets filter inverse correlation matrix"),
    ("获取或设置滤波器的增益系数矩阵", "Gets or sets filter gain coefficient matrix"),
    ("获取或设置滤波器计算的临时矩阵", "Gets or sets temporary matrix for filter computation"),
    ("获取或设置滤波器的步长因子", "Gets or sets filter step size"),
    ("获取或设置滤波器的泄漏因子", "Gets or sets filter leakage factor"),
    ("获取或设置滤波器链中的滤波器列表", "Gets or sets filter list in chain"),
    ("获取或设置左声道信号的滤波器", "Gets or sets left-channel filter"),
    ("获取或设置右声道信号的滤波器", "Gets or sets right-channel filter"),
    ("获取或设置滤波器的传递函数", "Gets or sets filter transfer function"),
    ("获取或设置截断脉冲响应的默认长度", "Gets or sets default truncated impulse response length"),
    ("获取或设置计算零点/极点（多项式根）的最大迭代次数。默认值为 25000",
     "Gets or sets max iterations for zero/pole computation. Default 25000"),
    ("获取或设置切换到重叠保存算法的最小核长度", "Gets or sets minimum kernel length for overlap-save"),
    ("获取滤波器核（脉冲响应）的副本", "Gets copy of filter kernel (impulse response)"),
    ("获取采样率（每秒的样本数）", "Gets sample rate (samples per second)"),
    ("获取复数值样本的实部", "Gets real part of complex sample"),
    ("获取复数值样本的虚部", "Gets imaginary part of complex sample"),
    ("获取复数值样本的幅度", "Gets magnitude of complex sample"),
    ("获取复数值样本的功率（幅度的平方）", "Gets power of complex sample (amplitude squared)"),
    ("获取复数值样本的相位", "Gets phase of complex sample"),
    ("获取复数值样本的展开相位", "Gets unwrapped phase of complex sample"),
    ("获取信号的长度", "Gets signal length"),
    ("获取信号是否开始淡出", "Gets whether fade-out has started"),
    ("获取信号是否完成淡出", "Gets whether fade-out has completed"),
    ("获取传递函数的分子", "Gets transfer function numerator"),
    ("获取传递函数的分母", "Gets transfer function denominator"),
    ("获取零点（'z' 在 'zpk' 表示法中）", "Gets zeros ('z' in zpk notation)"),
    ("获取极点（'p' 在 'zpk' 表示法中）", "Gets poles ('p' in zpk notation)"),
    ("获取增益（'k' 在 'zpk' 表示法中）", "Gets gain ('k' in zpk notation)"),
    ("获取或设置", "Gets or sets"),
    ("表示 ADSR 包络的状态", "Represents ADSR envelope state"),
    ("获取当前的 ADSR 状态（攻击、衰减、持续、释放）", "Gets current ADSR state (attack, decay, sustain, release)"),
    ("使用 ADSR 参数（以样本数表示）构造 AdsrBuilder 实例", "Constructs `AdsrBuilder` with ADSR parameters (in sample count)"),
    ("使用 ADSR 参数（以秒为单位）构造 AdsrBuilder 实例", "Constructs `AdsrBuilder` with ADSR parameters (in seconds)"),
    ("攻击阶段的样本数", "sample count for attack phase"),
    ("衰减阶段的样本数", "sample count for decay phase"),
    ("持续阶段的样本数", "sample count for sustain phase"),
    ("释放阶段的样本数", "sample count for release phase"),
    ("攻击阶段的持续时间（秒）", "attack phase duration (seconds)"),
    ("衰减阶段的持续时间（秒）", "decay phase duration (seconds)"),
    ("持续阶段的持续时间（秒）", "sustain phase duration (seconds)"),
    ("释放阶段的持续时间（秒）", "release phase duration (seconds)"),
    ("生成新的样本", "Generates the next sample"),
    ("重置样本生成器", "Resets the sample generator"),
    ("设置信号的采样率", "Sets the signal sample rate"),
    ("设置采样率后的 SignalBuilder 实例", "`SignalBuilder` after setting sample rate"),
    ("生成的样本", "generated sample"),
    ("设置淡入部分的持续时间（秒）", "Sets fade-in duration (seconds)"),
    ("设置淡出部分的持续时间（秒）", "Sets fade-out duration (seconds)"),
    ("设置谐波的振幅", "Sets harmonic amplitudes"),
    ("当前的 FadeInOutBuilder 实例", "current `FadeInOutBuilder` instance"),
    ("当前的 PadSynthBuilder 实例", "current `PadSynthBuilder` instance"),
    ("底层信号生成器", "underlying signal generator"),
    ("开始淡出", "Starts fade-out"),
    ("使用样本数组构造", "Constructs from sample array"),
    ("样本数组", "sample array"),
    ("波表样本数组", "wavetable sample array"),
    ("初始相位，默认值为", "initial phase; default"),
    ("反馈系数，默认值为", "feedback coefficient; default"),
    ("概率，默认值为", "probability; default"),
    ("拉伸因子，默认值为", "stretch factor; default"),
    ("带宽比例，默认值为", "bandwidth scale; default"),
    ("缩放比例，默认值为", "scale factor; default"),
    ("脉冲持续时间，默认值为", "pulse duration; default"),
    ("脉冲波周期，默认值为", "pulse wave period; default"),
    ("斜率，默认值为", "slope; default"),
    ("截距，默认值为", "intercept; default"),
    ("步长，默认值为", "step; default"),
    ("振幅数组", "amplitude array"),
    ("信号的采样率", "signal sample rate"),
    ("复数值信号的实部数组", "real-part array of complex signal"),
    ("复数值信号的虚部数组，默认为 null", "imaginary-part array of complex signal; default null"),
    ("复数值信号的实部集合", "real-part set of complex signal"),
    ("复数值信号的虚部集合，默认为 null", "imaginary-part set of complex signal; default null"),
    ("复数值样本集合", "complex sample set"),
    ("整数样本集合", "integer sample set"),
    ("如果应为数据分配新内存，则设置为 true，默认为 false",
     "if new memory should be allocated for data, set to true; default false"),
    ("每个样本的实部值，默认为 0.0", "real part value per sample; default 0.0"),
    ("每个样本的虚部值，默认为 0.0", "imaginary part value per sample; default 0.0"),
    ("每个样本将除以此值，默认为 1.0", "each sample is divided by this value; default 1.0"),
    ("具有指定长度并填充指定值的信号", "signal with specified length filled with specified value"),
    ("使用整数样本集合构造信号，并在给定采样率下进行归一化",
     "constructs signal from integer sample set and normalizes at given sample rate"),
    ("创建信号的深拷贝", "Creates a deep copy of the signal"),
    ("信号的深拷贝", "deep copy of the signal"),
    ("样本索引器。仅适用于样本实部数组。谨慎使用", "Sample indexer; applies to real-part array only; use with care"),
    ("样本索引", "sample index"),
    ("样本的实部值", "real part value of sample"),
    ("创建信号的切片", "Creates a slice of the signal"),
    ("第一个样本的索引（包含）", "index of first sample (inclusive)"),
    ("最后一个样本的索引（不包含）", "index of last sample (exclusive)"),
    ("信号的切片", "slice of the signal"),
    ("通过叠加信号 s1 和 s2 创建新信号。如果大小不同，则较小的信号将广播以适应较大的信号大小",
     "creates new signal by superimposing s1 and s2; if sizes differ, smaller signal is broadcast to match larger"),
    ("第一个信号", "first signal"),
    ("第二个信号", "second signal"),
    ("叠加后的新信号", "new superimposed signal"),
    ("通过将常数添加到信号 s 创建新信号", "creates new signal by adding constant to signal s"),
    ("要添加到每个样本的常数", "constant to add to each sample"),
    ("添加常数后的新信号", "new signal after adding constant"),
    ("通过从信号 s 中减去常数创建新信号", "creates new signal by subtracting constant from signal s"),
    ("要从每个样本中减去的常数", "constant to subtract from each sample"),
    ("减去常数后的新信号", "new signal after subtracting constant"),
    ("通过将信号 s 乘以系数（放大/衰减）创建新信号",
     "creates new signal by multiplying signal s by coefficient (amplify/attenuate)"),
    ("放大/衰减系数", "amplify/attenuate coefficient"),
    ("乘以系数后的新信号", "new signal after multiplying by coefficient"),
    ("从 `signal1` 中减去 `signal2`。如果大小不同，则较小的信号将广播以适应较大的信号大小",
     "Subtracts `signal2` from `signal1`; if sizes differ, smaller signal is broadcast to match larger"),
    ("减去后的 `DiscreteSignal`", "resulting `DiscreteSignal` after subtraction"),
    ("连接后的 `DiscreteSignal`", "concatenated `DiscreteSignal`"),
    ("重复后的 `DiscreteSignal`", "repeated `DiscreteSignal`"),
    ("新的 `DiscreteSignal`", "new `DiscreteSignal`"),
    ("全波整流 `signal`", "Full-wave rectifies `signal`"),
    ("半波整流 `signal`", "Half-wave rectifies `signal`"),
    ("按最大绝对值归一化 `signal`（范围 [-1, 1]）", "Normalizes `signal` by max absolute value (range [-1, 1])"),
    ("采样位深，默认为 0", "bits per sample; default 0"),
    ("从 `DiscreteSignal` 创建 `ComplexDiscreteSignal`，虚部将填充为零",
     "Creates `ComplexDiscreteSignal` from `DiscreteSignal` with zero imaginary part"),
    ("实值信号", "real-valued signal"),
    ("对 `signal` 进行线性淡入淡出", "Applies linear fade in/out to `signal`"),
    ("对 `signal` 进行线性淡入", "Applies linear fade in to `signal`"),
    ("对 `signal` 进行线性淡出", "Applies linear fade out to `signal`"),
    ("交叉淡化后的 `DiscreteSignal`", "crossfaded `DiscreteSignal`"),
    ("攻击阶段", "attack phase"),
    ("衰减阶段", "decay phase"),
    ("持续阶段", "sustain phase"),
    ("释放阶段", "release phase"),
    ("加性白高斯噪声（AWGN）", "additive white Gaussian noise (AWGN)"),
    ("周期性脉冲波", "periodic pulse waves"),
    ("直线信号", "ramp (linear) signals"),
    ("红噪声（布朗噪声）", "red noise (Brownian noise)"),
    ("粉红噪声", "pink noise"),
    ("基于波表的信号", "wavetable-based signals"),
    ("余弦信号", "cosine signals"),
    ("默认值为", "default"),
    ("构造函数", "constructor"),
    ("索引器", "Indexers"),
    ("运算符重载", "Operator overloads"),
    ("采样率", "sample rate"),
    ("样本数", "sample count"),
    ("时域", "time-domain"),
    ("频域", "frequency-domain"),
    ("零拷贝", "zero-copy"),
    ("已过时", "obsolete"),
    ("命名空间", "namespace"),
    ("滤波器", "filter"),
    ("卷积核", "kernel"),
    ("步长因子", "step size"),
    ("泄漏因子", "leakage factor"),
    ("输入信号", "input signal"),
    ("输出信号", "output signal"),
    ("期望信号", "desired signal"),
    ("载波信号", "carrier signal"),
    ("调制信号", "modulator signal"),
    ("截止频率", "cutoff frequency"),
    ("中心频率", "center frequency"),
    ("通带", "passband"),
    ("阻带", "stopband"),
    ("双二阶", "biquad"),
    ("巴特沃斯", "Butterworth"),
    ("切比雪夫", "Chebyshev"),
    ("椭圆", "elliptic"),
    ("贝塞尔", "Bessel"),
    ("最小均方", "least mean square"),
    ("最小均方四次", "least-mean-fourth"),
    ("归一化最小均方", "normalized least mean square"),
    ("递归最小二乘", "recursive least squares"),
    ("重叠相加", "overlap-add"),
    ("重叠保留", "overlap-save"),
    ("动态处理", "dynamics processing"),
    ("波形整形", "waveshaping"),
    ("谱减法", "spectral subtraction"),
    ("时间拉伸", "time stretch"),
    ("音高变换", "pitch shift"),
    ("实部", "real part"),
    ("虚部", "imaginary part"),
    ("复数", "complex"),
    ("离散信号", "discrete signal"),
    ("正弦波", "sine wave"),
    ("方波", "square wave"),
    ("锯齿波", "sawtooth wave"),
    ("三角波", "triangle wave"),
    ("白噪声", "white noise"),
    ("加性白高斯噪声", "additive white Gaussian noise"),
    ("窗函数", "window"),
    ("互相关", "cross-correlation"),
    ("反卷积", "deconvolution"),
    ("重采样", "resample"),
    ("淡入淡出", "fade in/out"),
    ("交叉淡化", "crossfade"),
    ("维纳滤波", "Wiener filtering"),
    ("移动平均", "moving average"),
    ("中值滤波", "median filtering"),
    ("梳状滤波", "comb filtering"),
    ("预加重", "pre-emphasis"),
    ("去加重", "de-emphasis"),
    ("直流去除", "DC removal"),
    ("传递函数", "transfer function"),
    ("群延迟", "group delay"),
    ("品质因数", "Q factor"),
    ("阻带衰减", "stopband attenuation"),
    ("通带增益", "passband gain"),
    ("概率", "probability"),
    ("振幅", "amplitude"),
    ("斜率", "slope"),
    ("截距", "intercept"),
    ("系数", "coefficient"),
    ("阈值", "threshold"),
    ("比率", "ratio"),
    ("补偿增益", "makeup gain"),
    ("攻击时间", "attack time"),
    ("释放时间", "release time"),
    ("最小振幅阈值", "minimum amplitude threshold"),
    ("噪声门", "noise gate"),
    ("限制器", "limiter"),
    ("压缩器", "compressor"),
    ("扩展器", "expander"),
    ("跳跃长度", "hop length"),
    ("跳跃大小", "hop size"),
    ("掩蔽模式", "masking mode"),
    ("滤波方法", "filtering method"),
    ("深拷贝", "deep copy"),
    ("整数", "integer"),
    ("切片", "slice"),
    ("展开", "unwrapped"),
    ("平方", "squared"),
    ("长度", "length"),
    ("填充", "filled"),
    ("广播", "broadcast"),
    ("适应", "match"),
    ("减去", "subtract"),
    ("乘以", "multiply"),
    ("放大", "amplify"),
    ("衰减", "attenuation"),
    ("谨慎", "care"),
    ("索引", "index"),
    ("包含", "inclusive"),
    ("不包含", "exclusive"),
    ("叠加", "superimpose"),
    ("常数", "constant"),
    ("新信号", "new signal"),
    ("新内存", "new memory"),
    ("内存", "memory"),
    ("数据", "data"),
    ("分配", "allocate"),
    ("设置为", "set to"),
    ("阶段", "phase"),
    ("因子", "factor"),
    ("大小", "size"),
    ("时间", "time"),
    ("数组", "array"),
    ("集合", "set"),
    ("权重", "weight"),
    ("响应", "response"),
    ("模式", "mode"),
    ("类型", "type"),
    ("形式", "form"),
    ("结果", "result"),
    ("方法", "method"),
    ("属性", "property"),
    ("实例", "instance"),
    ("信号", "signal"),
    ("样本", "sample"),
    ("频率", "frequency"),
    ("幅度", "amplitude"),
    ("相位", "phase"),
    ("功率", "power"),
    ("能量", "energy"),
    ("卷积", "convolution"),
    ("调制", "modulation"),
    ("包络", "envelope"),
    ("谐波", "harmonic"),
    ("打击乐", "percussive"),
    ("分离", "separation"),
    ("重建", "reconstruction"),
    ("自适应", "adaptive"),
    ("算法", "algorithm"),
    ("增益", "gain"),
    ("阶数", "order"),
    ("带宽", "bandwidth"),
    ("纹波", "ripple"),
    ("极点", "poles"),
    ("零点", "zeros"),
    ("原型", "prototype"),
    ("峰值", "peak"),
    ("区间", "range"),
    ("特征", "features"),
    ("统计", "statistics"),
    ("熵", "entropy"),
    ("整流", "rectification"),
    ("连接", "concatenate"),
    ("反转", "reverse"),
    ("延迟", "delay"),
    ("噪声", "noise"),
    ("直流", "DC"),
    ("低通", "low-pass"),
    ("高通", "high-pass"),
    ("带通", "band-pass"),
    ("带阻", "band-stop"),
    ("插值", "interpolation"),
    ("归一化", "normalize"),
    ("推荐", "recommended"),
    ("实现", "implements"),
    ("继承", "inherits"),
    ("表示", "Represents"),
    ("生成", "Generates"),
    ("获取", "Gets"),
    ("返回", "Returns"),
    ("计算", "Computes"),
    ("执行", "Performs"),
    ("初始化", "Initializes"),
    ("构造", "Constructs"),
    ("创建", "Creates"),
    ("设置", "Sets"),
    ("重置", "Resets"),
    ("使用", "Uses"),
    ("判断", "Determines whether"),
    ("处理", "Processes"),
    ("应用", "Applies"),
    ("设计", "Designs"),
    ("训练", "Trains"),
    ("预测", "Predicts"),
    ("估计", "Estimates"),
    ("更新", "Updates"),
    ("添加", "Adds"),
    ("保存", "Saves"),
    ("加载", "Loads"),
    ("滤波", "Filters"),
    ("在线", "Online"),
    ("离线", "offline"),
    ("静态", "static"),
    ("抽象", "abstract"),
    ("泛型", "generic"),
    ("只读", "readonly"),
    ("公开", "public"),
    ("可选", "optional"),
    ("当前", "current"),
    ("底层", "underlying"),
    ("输入", "input"),
    ("输出", "output"),
    ("期望", "desired"),
    ("载波", "carrier"),
    ("步长", "step"),
    ("泄漏", "leakage"),
    ("占空比", "duty cycle"),
    ("均值", "mean"),
    ("标准差", "standard deviation"),
    ("结构", "struct"),
    ("枚举", "enum"),
    ("接口", "interface"),
    ("是一个用于实现带通贝塞尔滤波器的类", "implements a band-pass Bessel filter"),
    ("是一个用于实现带阻贝塞尔滤波器的类", "implements a band-stop Bessel filter"),
    ("是一个用于实现高通贝塞尔滤波器的类", "implements a high-pass Bessel filter"),
    ("是一个用于实现低通贝塞尔滤波器的类", "implements a low-pass Bessel filter"),
    ("是一个用于实现双二阶全通滤波器的类", "implements a biquad all-pass filter"),
    ("是一个用于实现双二阶带通滤波器的类", "implements a biquad band-pass filter"),
    ("是一个用于实现双二阶 IIR 滤波器的类", "implements a biquad IIR filter"),
    ("是一个用于实现双二阶高通滤波器的类", "implements a biquad high-pass filter"),
    ("是一个用于实现双二阶高架滤波器的类", "implements a biquad high-shelf filter"),
    ("是一个用于实现双二阶低通滤波器的类", "implements a biquad low-pass filter"),
    ("是一个用于实现双二阶低架滤波器的类", "implements a biquad low-shelf filter"),
    ("是一个用于实现双二阶陷波滤波器的类", "implements a biquad notch filter"),
    ("是一个用于实现双二阶峰值均衡滤波器的类", "implements a biquad peak EQ filter"),
    ("是一个用于实现带通巴特沃斯滤波器的类", "implements a band-pass Butterworth filter"),
    ("是一个用于实现带阻巴特沃斯滤波器的类", "implements a band-stop Butterworth filter"),
    ("是一个用于实现高通巴特沃斯滤波器的类", "implements a high-pass Butterworth filter"),
    ("是一个用于实现低通巴特沃斯滤波器的类", "implements a low-pass Butterworth filter"),
    ("是一个用于实现带通切比雪夫-I型滤波器的类", "implements a band-pass Chebyshev type I filter"),
    ("是一个用于实现带阻切比雪夫-I型滤波器的类", "implements a band-stop Chebyshev type I filter"),
    ("是一个用于实现高通切比雪夫-I型滤波器的类", "implements a high-pass Chebyshev type I filter"),
    ("是一个用于实现低通切比雪夫-I型滤波器的类", "implements a low-pass Chebyshev type I filter"),
    ("是一个用于生成切比雪夫-I型滤波器原型的静态类", "is a static class that generates Chebyshev type I filter prototypes"),
    ("是一个用于实现带通切比雪夫-II型滤波器的类", "implements a band-pass Chebyshev type II filter"),
    ("是一个用于实现带阻切比雪夫-II型滤波器的类", "implements a band-stop Chebyshev type II filter"),
    ("是一个用于实现高通切比雪夫-II型滤波器的类", "implements a high-pass Chebyshev type II filter"),
    ("是一个用于实现低通切比雪夫-II型滤波器的类", "implements a low-pass Chebyshev type II filter"),
    ("是一个用于生成切比雪夫-II型滤波器原型的静态类", "is a static class that generates Chebyshev type II filter prototypes"),
    ("是一个用于实现带通椭圆滤波器的类", "implements a band-pass elliptic filter"),
    ("是一个用于实现有限脉冲响应（Finite Impulse Response, FIR）滤波器的类", "implements a finite impulse response (FIR) filter"),
    ("是一个用于实现无限脉冲响应（Infinite Impulse Response, IIR）滤波器的类", "implements an infinite impulse response (IIR) filter"),
    ("是一个用于实现顺序连接滤波器链的类", "implements a serial filter chain"),
    ("是一个用于处理交错立体声缓冲区数据的滤波器类", "filters interleaved stereo buffer data"),
    ("是一个用于表示线性时不变（LTI）滤波器传递函数的类", "represents an LTI filter transfer function"),
    ("是一个基于状态向量实现的 LTI 滤波器的特殊实现", "is a state-vector-based LTI filter implementation"),
    ("是一个用于信号重采样（采样率转换）的类", "performs signal resampling (sample-rate conversion)"),
    ("是一个用于实现谱减法滤波的类", "implements spectral subtraction filtering"),
    ("是一个用于波形整形的类", "performs waveshaping"),
    ("获取低截止频率", "Gets low cutoff frequency"),
    ("获取高截止频率", "Gets high cutoff frequency"),
    ("获取 Q 因子", "Gets Q factor"),
    ("获取纹波（以 dB 为单位）", "Gets ripple (dB)"),
    ("获取通带纹波（以 dB 为单位）", "Gets passband ripple (dB)"),
    ("获取阻带纹波（以 dB 为单位）", "Gets stopband ripple (dB)"),
    ("获取架频率", "Gets shelf frequency"),
    ("获取增益（以 dB 为单位）", "Gets gain (dB)"),
    ("获取状态向量", "Gets state vector"),
    ("获取状态空间表示", "Gets state-space representation"),
    ("获取与阶跃响应的稳态对应的初始状态", "Gets initial state corresponding to step-response steady state"),
    ("构造具有给定阶数和截止频率的", "Constructs with given order and cutoff frequency"),
    ("构造一个给定阶数的", "Constructs with given order"),
    ("构造一个默认的 BiQuadFilter 实例，使用默认系数", "Constructs default `BiQuadFilter` with default coefficients"),
    ("从滤波器系数（分子 {B0, B1, B2} 和分母 {A0, A1, A2}）构造 BiQuadFilter 实例",
     "Constructs `BiQuadFilter` from coefficients (numerator {B0, B1, B2}, denominator {A0, A1, A2})"),
    ("归一化低截止频率，范围 [0..0.5]", "normalized low cutoff frequency, range [0..0.5]"),
    ("归一化高截止频率，范围 [0..0.5]", "normalized high cutoff frequency, range [0..0.5]"),
    ("归一化截止频率，范围 [0..0.5]", "normalized cutoff frequency, range [0..0.5]"),
    ("归一化中心频率，范围 [0..0.5]", "normalized center frequency, range [0..0.5]"),
    ("归一化架频率，范围 [0..0.5]", "normalized shelf frequency, range [0..0.5]"),
    ("增益（以 dB 为单位），默认为 1.0f", "gain (dB); default 1.0f"),
    ("增益（以 dB 为单位）", "gain (dB)"),
    ("纹波（以 dB 为单位），默认为 0.1f", "ripple (dB); default 0.1f"),
    ("纹波（以 dB 为单位）", "ripple (dB)"),
    ("Q 因子，默认为 1", "Q factor; default 1"),
    ("Q 因子", "Q factor"),
    ("生成的 `TransferFunction` 对象", "generated `TransferFunction`"),
    ("更改滤波器系数（保持滤波器状态）", "changes filter coefficients (preserves filter state)"),
    ("在线更改滤波器系数（保持滤波器状态）", "changes filter coefficients online (preserves state)"),
    ("设置滤波器系数", "sets filter coefficients"),
    ("计算给定阶数的贝塞尔滤波器的模拟极点", "computes analog poles of Bessel filter of given order"),
    ("计算给定阶数的巴特沃斯滤波器的模拟极点", "computes analog poles of Butterworth filter of given order"),
    ("计算给定阶数的切比雪夫-I型滤波器的模拟极点", "computes analog poles of Chebyshev type I filter of given order"),
    ("计算给定阶数的切比雪夫-II型滤波器的模拟极点", "computes analog poles of Chebyshev type II filter of given order"),
    ("计算给定阶数的切比雪夫-II型滤波器的模拟零点", "computes analog zeros of Chebyshev type II filter of given order"),
    ("包含巴特沃斯滤波器极点的 ComplexFp32 数组", "`ComplexFp32` array of Butterworth filter poles"),
    ("包含切比雪夫-I型滤波器极点的 ComplexFp32 数组", "`ComplexFp32` array of Chebyshev type I filter poles"),
    ("包含切比雪夫-II型滤波器极点的 ComplexFp32 数组", "`ComplexFp32` array of Chebyshev type II filter poles"),
    ("包含切比雪夫-II型滤波器零点的 ComplexFp32 数组", "`ComplexFp32` array of Chebyshev type II filter zeros"),
    ("极点数组", "pole array"),
    ("第 k 个系数", "k-th coefficient"),
    ("系数的索引", "coefficient index"),
    ("贝塞尔多项式的阶数", "Bessel polynomial order"),
    ("获取 n 阶贝塞尔多项式的第 k 个系数", "Gets k-th coefficient of n-th order Bessel polynomial"),
    ("传递函数的分子", "transfer function numerator"),
    ("传递函数的分母", "transfer function denominator"),
    ("传递函数的分母，默认为 `[1.0f]`", "transfer function denominator; default `[1.0f]`"),
    ("状态空间表示", "state-space representation"),
    ("初始条件向量", "initial condition vector"),
    ("脉冲响应的长度", "impulse response length"),
    ("脉冲响应数组", "impulse response array"),
    ("频率响应的长度", "frequency response length"),
    ("频率响应的 `ComplexDiscreteSignal` 对象", "`ComplexDiscreteSignal` of frequency response"),
    ("群延迟数组的长度", "group delay array length"),
    ("群延迟数组", "group delay array"),
    ("相位延迟数组的长度", "phase delay array length"),
    ("相位延迟数组", "phase delay array"),
    ("计算给定长度的脉冲响应", "computes impulse response of given length"),
    ("计算给定长度的频率响应", "computes frequency response of given length"),
    ("计算给定长度的群延迟", "computes group delay of given length"),
    ("计算给定长度的相位延迟", "computes phase delay of given length"),
    ("在给定频率处归一化频率响应（将分子归一化以将频率响应映射到 [0, 1]）",
     "normalizes frequency response at given frequency (maps to [0, 1])"),
    ("归一化分子和分母（将它们除以分母的第一个系数）",
     "normalizes numerator and denominator (divide by first denominator coefficient)"),
    ("创建两个传递函数的串联连接", "creates series connection of two transfer functions"),
    ("创建两个传递函数的并联连接", "creates parallel connection of two transfer functions"),
    ("第一个传递函数", "first transfer function"),
    ("第二个传递函数", "second transfer function"),
    ("串联连接的传递函数", "series-connected transfer function"),
    ("并联连接的传递函数", "parallel-connected transfer function"),
    ("从 CSV 流加载传递函数的分子和分母", "loads transfer function numerator/denominator from CSV stream"),
    ("将传递函数的分子和分母序列化到 CSV 流", "serializes transfer function numerator/denominator to CSV stream"),
    ("输入流", "input stream"),
    ("输出流", "output stream"),
    ("分隔符，默认为 `,`", "delimiter; default `,`"),
    ("执行零相位滤波", "performs zero-phase filtering"),
    ("在应用滤波器之前在两端扩展信号的元素数量", "number of elements to pad at both ends before filtering"),
    ("从分子和分母构造 TransferFunction 实例", "constructs `TransferFunction` from numerator and denominator"),
    ("从零点、极点和增益构造 TransferFunction 实例", "constructs `TransferFunction` from zeros, poles, and gain"),
    ("从状态空间表示构造 TransferFunction 实例", "constructs `TransferFunction` from state-space representation"),
    ("从分子和分母系数构造 IirFilter 实例", "constructs `IirFilter` from numerator and denominator coefficients"),
    ("从 64 位分子和分母系数构造 IirFilter 实例", "constructs `IirFilter` from 64-bit numerator/denominator coefficients"),
    ("从传递函数构造 IirFilter 实例", "constructs `IirFilter` from transfer function"),
    ("从给定的核构造 FirFilter 实例", "constructs `FirFilter` from given kernel"),
    ("从 64 位核构造 FirFilter 实例", "constructs `FirFilter` from 64-bit kernel"),
    ("从传递函数构造 FirFilter 实例", "constructs `FirFilter` from transfer function"),
    ("处理所有样本", "processes all samples"),
    ("处理后的样本数组", "processed sample array"),
    ("直接应用滤波器", "applies filter directly"),
    ("更改滤波器核", "changes filter kernel"),
    ("新的核", "new kernel"),
    ("新的分子系数", "new numerator coefficients"),
    ("新的分母系数", "new denominator coefficients"),
    ("新的传递函数", "new transfer function"),
    ("传递函数的分子系数", "transfer function numerator coefficients"),
    ("传递函数的分母系数", "transfer function denominator coefficients"),
    ("创建两个 FIR 滤波器的串联连接", "creates series connection of two FIR filters"),
    ("创建 FIR 滤波器和 IIR 滤波器的串联连接", "creates series connection of FIR and IIR filters"),
    ("创建两个 FIR 滤波器的并联连接", "creates parallel connection of two FIR filters"),
    ("创建 FIR 滤波器和 IIR 滤波器的并联连接", "creates parallel connection of FIR and IIR filters"),
    ("创建 IIR 滤波器和任意 LTI 滤波器的串联连接", "creates series connection of IIR and arbitrary LTI filter"),
    ("创建 IIR 滤波器和任意 LTI 滤波器的并联连接", "creates parallel connection of IIR and arbitrary LTI filter"),
    ("第一个 FIR 滤波器", "first FIR filter"),
    ("第二个 FIR 滤波器", "second FIR filter"),
    ("串联连接的 FIR 滤波器", "series-connected FIR filter"),
    ("串联连接的 IIR 滤波器", "series-connected IIR filter"),
    ("并联连接的 FIR 滤波器", "parallel-connected FIR filter"),
    ("并联连接的 IIR 滤波器", "parallel-connected IIR filter"),
    ("左声道信号的滤波器", "left-channel filter"),
    ("右声道信号的滤波器", "right-channel filter"),
    ("内部标志，用于在左声道和右声道之间切换", "internal flag toggling left/right channel"),
    ("从两个独立的滤波器构造 StereoFilter 实例", "constructs `StereoFilter` from two independent filters"),
    ("从在线滤波器集合构造 FilterChain 实例", "constructs `FilterChain` from online filter collection"),
    ("在线滤波器集合，默认为空", "online filter collection; default empty"),
    ("从传递函数集合（例如，SOS 段）构造 FilterChain 实例", "constructs `FilterChain` from transfer function set (e.g. SOS sections)"),
    ("传递函数集合", "transfer function set"),
    ("将滤波器添加到链中", "adds filter to chain"),
    ("在链中指定索引处插入滤波器", "inserts filter at index in chain"),
    ("滤波器在链中的索引", "filter index in chain"),
    ("从链中移除指定索引处的滤波器", "removes filter at index from chain"),
    ("通过滤波器链处理一个样本", "processes one sample through filter chain"),
    ("重置链中的所有滤波器", "resets all filters in chain"),
    ("将滤波器应用于整个信号，并返回新的滤波信号", "applies filter to entire signal and returns new filtered signal"),
    ("过滤方法，默认为 `FilteringMethod.Auto`", "filtering method; default `FilteringMethod.Auto`"),
    ("处理输入和期望信号的一个样本，并自适应调整滤波器系数",
     "processes one input/desired sample and adaptively updates filter coefficients"),
    ("输入信号的样本", "input signal sample"),
    ("期望信号的样本", "desired signal sample"),
    ("滤波器输出的样本", "filter output sample"),
    ("归一化因子，默认值为 1", "normalization factor; default 1"),
    ("遗忘因子，默认值为 0.99", "forgetting factor; default 0.99"),
    ("初始化逆相关矩阵的值，默认值为 1e2f", "initial inverse correlation matrix value; default 1e2f"),
    ("步长因子数组，默认为每个阶数 0.75", "step-size array; default 0.75 per order"),
    ("以下是一个使用 PrototypeButterworth 类中 Poles 方法的示例，并在示例中加入了注释：",
     "The following example uses `PrototypeButterworth.Poles` with comments:"),
    ("以下是一个使用 PrototypeChebyshevI 类中 Poles 方法的示例，并在示例中加入了注释：",
     "The following example uses `PrototypeChebyshevI.Poles` with comments:"),
    ("以下是一个使用 PrototypeChebyshevII 类中 Poles 和 Zeros 方法的示例，并在示例中加入了注释：",
     "The following example uses `PrototypeChebyshevII.Poles` and `Zeros` with comments:"),
    ("定义低截止频率、高截止频率和滤波器阶数", "low/high cutoff frequencies and filter order"),
    ("定义截止频率和滤波器阶数", "cutoff frequency and filter order"),
    ("定义中心频率和 Q 因子", "center frequency and Q factor"),
    ("定义架频率、Q 因子和增益", "shelf frequency, Q factor, and gain"),
    ("定义中心频率、Q 因子和增益", "center frequency, Q factor, and gain"),
    ("更改滤波器的截止频率", "change filter cutoff frequency"),
    ("更改滤波器的低截止频率和高截止频率", "change filter low/high cutoff frequencies"),
    ("更改滤波器的中心频率和 Q 因子", "change filter center frequency and Q factor"),
    ("更改滤波器的架频率、Q 因子和增益", "change filter shelf frequency, Q factor, and gain"),
    ("更改滤波器的系数", "change filter coefficients"),
    ("定义传递函数的分子和分母", "transfer function numerator and denominator"),
    ("定义滤波器核", "filter kernel"),
    ("定义滤波器的分子和分母系数", "filter numerator and denominator coefficients"),
    ("定义滤波器阶数、步长因子和泄漏因子", "filter order, step size, and leakage factor"),
    ("定义输入信号和期望信号", "input and desired signals"),
    ("处理信号并输出结果", "process signal and print result"),
    ("创建一些示例滤波器", "example filters"),
    ("创建 FilterChain 实例并添加滤波器", "create `FilterChain` and add filters"),
    ("啁啾信号", "chirp signals"),
    ("生成样本并输出", "samples and print"),
    ("重置样本生成器", "sample generator"),
    ("使用秒数构造 AdsrBuilder 实例", "AdsrBuilder with seconds"),
    ("使用样本数构造 AdsrBuilder 实例", "AdsrBuilder with sample count"),
    ("是一个用于生成加性白高斯噪声（AWGN）的类，继承了 SignalBuilder 类。使用 Box-Muller 变换生成加性白高斯噪声。",
     "generates additive white Gaussian noise (AWGN); inherits `SignalBuilder`. Uses Box–Muller transform."),
    ("生成信号，通过逐个生成所有样本", "generates signal sample by sample"),
    ("卷积结果的", "convolution result "),
    ("互相关结果的", "cross-correlation result "),
    ("反卷积结果的", "deconvolution result "),
    ("进行快速卷积", "for fast convolution"),
    ("进行快速互相关", "for fast cross-correlation"),
    ("进行快速反卷积", "for fast deconvolution"),
    ("并将结果存储在", "and stores result in"),
    ("数组中", "array"),
    ("指定卷积核和 FFT 大小", "specifying kernel and FFT size"),
    ("构造一个给定阶数的", "Constructs with given order "),
    ("归一化因子", "normalization factor"),
    ("遗忘因子", "forgetting factor"),
    ("逆相关矩阵", "inverse correlation matrix"),
    ("增益系数矩阵", "gain coefficient matrix"),
    ("临时矩阵", "temporary matrix"),
    ("最小均方四次", "least-mean-fourth"),
    ("并自适应调整滤波器系数", "and adaptively updates filter coefficients"),
    ("输入和期望信号的一个样本", "one input/desired sample"),
    ("滤波器输出的样本", "filter output sample"),
    ("定义输入信号和", "Define input signal and "),
    ("定义滤波器阶数、步长因子和泄漏因子", "filter order, step size, and leakage factor"),
    ("处理信号并输出结果", "Process signal and print result"),
]
PHRASES = [(zh, en) for zh, en in PHRASES if len(zh) >= 4 or zh.startswith(("  -", "        //", '- `"', "####", "- :"))]
PHRASES.sort(key=lambda x: len(x[0]), reverse=True)

CLASS_PATTERNS = list(gen.CLASS_PATTERNS)
COMMENT_RE = list(gen.COMMENT_RE)

PREFIX_RULES = [
    (r"^  - 获取或设置(.+)$", "  - Gets or sets {}."),
    (r"^  - 获取(.+)$", "  - Gets {}."),
    (r"^  - 返回(.+)$", "  - Returns {}."),
    (r"^  - 计算(.+)$", "  - Computes {}."),
    (r"^  - 执行(.+)$", "  - Performs {}."),
    (r"^  - 使用(.+)$", "  - Uses {}."),
    (r"^  - 创建(.+)$", "  - Creates {}."),
    (r"^  - 构造(.+)$", "  - Constructs {}."),
    (r"^  - 设置(.+)$", "  - Sets {}."),
    (r"^  - 重置(.+)$", "  - Resets {}."),
    (r"^  - 生成(.+)$", "  - Generates {}."),
    (r"^  - 应用(.+)$", "  - Applies {}."),
    (r"^  - 设计(.+)$", "  - Designs {}."),
    (r"^  - 训练(.+)$", "  - Trains {}."),
    (r"^  - 预测(.+)$", "  - Predicts {}."),
    (r"^  - 更新(.+)$", "  - Updates {}."),
    (r"^  - 初始化(.+)$", "  - Initializes {}."),
    (r"^  - 处理(.+)$", "  - Processes {}."),
    (r"^  - 滤波(.+)$", "  - Filters {}."),
    (r"^  - 判断(.+)$", "  - Determines whether {}."),
    (r"^  - 表示(.+)$", "  - Represents {}."),
    (r"^  - 估计(.+)$", "  - Estimates {}."),
    (r"^  - 展开(.+)$", "  - Unwraps {}."),
    (r"^  - 连接(.+)$", "  - Concatenates {}."),
    (r"^  - 叠加(.+)$", "  - Superimposes {}."),
    (r"^  - 按 (.+)$", "  - By {}."),
    (r"^  - 从 (.+)$", "  - From {}."),
    (r"^  - 对 (.+)$", "  - On {}."),
    (r"^  - 将(.+)$", "  - {}."),
    (r"^  - 在(.+)$", "  - At {}."),
    (r"^  - 把(.+)$", "  - {}."),
    (r"^  - 给(.+)$", "  - {}."),
    (r"^  - 向(.+)$", "  - To {}."),
    (r"^  - 为(.+)$", "  - For {}."),
    (r"^  - 返回值: (.+)$", "  - Returns: {}"),
    (r"^  - 返回值: (.+)。$", "  - Returns: {}."),
    (r"^    - `([^`]+)`: (.+)$", "    - `{}`: {}."),
    (r"^- `\"([^\"]+)\"[^:]*: (.+)$", '- `"{}"`: {}.'),
    (r"^#### (\d+)\. (.+?) 构造函数$", "#### {}. {} constructor"),
    (r"^#### (\d+)\. 索引器$", "#### {}. Indexers"),
    (r"^#### (\d+)\. 运算符重载$", "#### {}. Operator overloads"),
    (r"^        // (.+)$", "        // {}"),
]


def apply_phrases(text: str) -> str:
    for zh, en in PHRASES:
        if zh in text:
            text = text.replace(zh, en)
    return text


def translate_tail(text: str) -> str:
    text = text.rstrip("。").rstrip("：").strip()
    text = text.replace("，", ", ")
    text = text.replace("。", ".")
    text = text.replace("：", ": ")
    text = text.replace("（", " (")
    text = text.replace("）", ")")
    text = text.replace("、", ", ")
    text = text.replace("；", "; ")
    text = re.sub(r"\s+", " ", text).strip()
    if text and text[-1] not in ".!?":
        if not text.endswith(")") and not text.endswith("`"):
            text += "."
    return text


def translate_line(line: str) -> str:
    line = gen.fix_links(line)
    if line in gen.EXACT:
        return gen.fix_anchors(gen.EXACT[line])
    # Exact full-line match
    for zh, en in PHRASES:
        if line == zh:
            return gen.fix_anchors(en)

    out = line
    for pat, repl in CLASS_PATTERNS:
        o2 = re.sub(pat, repl, out)
        if o2 != out:
            out = o2
            break
    for pat, repl in COMMENT_RE:
        o2 = re.sub(pat, repl, out)
        if o2 != out:
            out = o2
            break

    if re.search(r"[\u4e00-\u9fff]", out):
        for pat, tmpl in PREFIX_RULES:
            m = re.match(pat, out)
            if m:
                groups = [translate_tail(g) for g in m.groups()]
                if "{}" in tmpl:
                    out = tmpl.format(*groups)
                else:
                    out = re.sub(pat, tmpl, out)
                break
        else:
            out = translate_tail(out)

    out = gen.fix_anchors(out)
    return out


def build_all() -> dict[str, str]:
    data = json.loads((ROOT / "tools" / "sp_unique_cn_lines.json").read_text(encoding="utf-8"))
    lines = []
    for v in data.values():
        lines.extend(v)
    seen = set()
    unique = []
    for l in lines:
        if l not in seen:
            seen.add(l)
            unique.append(l)
    return {l: translate_line(l) for l in unique}


if __name__ == "__main__":
    mapping = build_all()
    out_path = ROOT / "tools" / "sp_manual_overrides.json"
    # only store lines that differ from generator and have no Chinese
    gen_map = json.loads((ROOT / "tools" / "sp_exact_translations.json").read_text(encoding="utf-8"))
    overrides = {}
    for k, v in mapping.items():
        if not re.search(r"[\u4e00-\u9fff]", v):
            overrides[k] = v
    out_path.write_text(json.dumps(overrides, ensure_ascii=False, indent=2), encoding="utf-8")
    remaining = [k for k, v in mapping.items() if re.search(r"[\u4e00-\u9fff]", v)]
    print(f"Clean overrides: {len(overrides)}, remaining: {len(remaining)}")
