#!/usr/bin/env python3
"""Second pass: fix remaining Chinese in Batch C wiki files."""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN = ROOT / "wiki_en"
REMAINING = ROOT / "tools" / "remaining_chinese_lines.json"

FILES = [
    "Module_MachineLearning.md",
    "Module_LinearAlgebra.md",
    "Module_Experimental.md",
]

# Full-line exact translations for remaining lines
EXACT = json.loads(REMAINING.read_text(encoding="utf-8"))
EXACT_MAP = {
    "            // 脱离为独立信号": "            // Decouple to standalone signal",
    "        // 创建信号（1000 个采样，采样率 44100）": "        // Create signal (1000 samples, 44100 Hz)",
    "        // 创建卡尔曼滤波器实例": "        // Create Kalman filter",
    "        // 创建无迹卡尔曼滤波器实例": "        // Create unscented Kalman filter",
    "        // 叠加方波": "        // Add square wave",
    "        // 叠加白噪声": "        // Add white noise",
    "        // 合并两个矩阵": "        // Combine two matrices",
    "        // 四元数乘法": "        // Quaternion multiplication",
    "        // 四元数共轭": "        // Quaternion conjugate",
    "        // 四元数减法": "        // Quaternion subtraction",
    "        // 四元数加法": "        // Quaternion addition",
    "        // 四元数归一化": "        // Quaternion normalization",
    "        // 四元数范数": "        // Quaternion norm",
    "        // 四元数逆": "        // Quaternion inverse",
    "        // 四元数除法": "        // Quaternion division",
    "        // 多项式回归": "        // Polynomial regression",
    "        // 定义两个二维数组矩阵 ": "        // Two 2D array matrices",
    "        // 定义两个锯齿数组矩阵": "        // Two jagged matrices",
    "        // 定义二维数组 ": "        // 2D array",
    "        // 定义四元数 ": "        // Quaternions",
    "        // 定义张量 ": "        // Tensor",
    "        // 定义时域信号": "        // Time-domain signal",
    "        // 将时域信号转换为频域信号": "        // Transform to frequency domain",
    "        // 张量乘法": "        // Tensor multiply",
    "        // 张量克隆": "        // Clone tensor",
    "        // 张量减法": "        // Tensor subtract",
    "        // 张量切片": "        // Tensor slice",
    "        // 张量加法": "        // Tensor add",
    "        // 张量和": "        // Tensor sum",
    "        // 张量归一化": "        // Normalize tensor",
    "        // 张量点积": "        // Tensor dot product",
    "        // 张量范数": "        // Tensor norm",
    "        // 张量转置": "        // Transpose tensor",
    "        // 指数回归": "        // Exponential regression",
    "        // 生成正弦波": "        // Generate sine wave",
    "        // 生成正弦波并替换现有信号": "        // Generate sine wave (replace)",
    "        // 线性回归": "        // Linear regression",
    "        // 获取信号段（第 1000 个采样开始，取 5000 个采样）": "        // Get segment (from sample 1000, length 5000)",
    "        // 获取子矩阵": "        // Get submatrix",
    "        // 获取满足条件的元素的索引": "        // Get indexes of matching elements",
    "        // 获取矩阵的转置": "        // Get matrix transpose",
    "        // 转换为频域": "        // Transform to frequency domain",
    "        // 输出时域信号的属性": "        // Print time-domain properties",
    "        // 输出频域信号的属性": "        // Print frequency-domain properties",
    "        // 重采样": "        // Resample",
    "        // 锯齿数组矩阵乘法": "        // Jagged matrix multiply",
    "      // 创建平方根卡尔曼滤波器实例": "      // Create square-root Kalman filter",
    "    当前位置 : [首页](HOME.md)/[机器学习模块](Module_MachineLearning.md)":
        "Location: [Home](HOME.md) / [Machine learning](Module_MachineLearning.md)",
    "当前位置 : [首页](HOME.md)/[线性代数模块](Module_LinearAlgebra.md)":
        "Location: [Home](HOME.md) / [Linear algebra](Module_LinearAlgebra.md)",
    "当前位置 : [首页](HOME.md)/[实验性模块](Module_Experimental.md)":
        "Location: [Home](HOME.md) / [Experimental](Module_Experimental.md)",
    "    { // 定义滤波器参数": "    { // Filter parameters",
    "// 分类": "// Classification",
    "### 要点": "### Notes",
    "### 重写方法": "### Overrides",
    "## DataRow&lt;T> struct体": "## DataRow&lt;T> struct",
    "## FrequencyDomain struct体": "## FrequencyDomain struct",
    "## SignalSegment struct体": "## SignalSegment struct",
    "**Softmax / Logistic mini-batch 训练**": "**Softmax / Logistic mini-batch training**",
    "- :bookmark: [Module overview and new APIs](#module-overview-and-new-apis)（见上文表格）":
        "- :bookmark: [Module overview and new APIs](#module-overview-and-new-apis) (see table above)",
    "- :bookmark: [DataRow&lt;T> struct体](#datarowt-结构体)": "- :bookmark: [DataRow&lt;T> struct](#datarowt-struct)",
    "- :bookmark: [FrequencyDomain struct体](#frequencydomain-结构体)": "- :bookmark: [FrequencyDomain struct](#frequencydomain-struct)",
    "- :bookmark: [SignalSegment struct体](#signalsegment-结构体)": "- :bookmark: [SignalSegment struct](#signalsegment-struct)",
    "NHWC 张量布局工具，供卷积 im2col 等路径复用。": "NHWC tensor layout utilities reused by convolution im2col paths.",
    "矩阵数值诊断工具。": "Matrix numerical diagnostics utilities.",
    "矩阵与列向量相乘请使用 `Matrix<T>.Multiply(ReadOnlySpan<T>)` 或 `Multiply(vector, result)`。":
        "For matrix–column-vector multiply use `Matrix<T>.Multiply(ReadOnlySpan<T>)` or `Multiply(vector, result)`.",
    "单精度遗留类型 `Matrix`（`Matrix_f.cs`）提供相同求解/诊断 API，并通过 `ToGeneric()` / 隐式转换与 `Matrix<float>` 互操作。":
        "Legacy single-precision `Matrix` (`Matrix_f.cs`) exposes the same solve/diagnostics APIs and interoperates with `Matrix<float>` via `ToGeneric()` / implicit conversion.",
    "布局中性的 4 维张量（Dim0–Dim3），连续 `Memory<T>` 存储。深度学习中的 `BatchTensor<T>` 将 N→Dim0、H→Dim1、W→Dim2、C→Dim3 映射到同一存储。":
        "Layout-neutral 4D tensor (Dim0–Dim3) with contiguous `Memory<T>` storage. Deep learning `BatchTensor<T>` maps N→Dim0, H→Dim1, W→Dim2, C→Dim3 onto the same storage.",
    "以下示例使用二维数值特征与整数类别标签（`0`、`1`、`2`），与 `Examples/MachineLearning_example` 及 `TESTS/ML_module_test` 中的用法一致。所有分类器均实现 `IClassifier<T>`，统一调用 `Fit(x, y)` / `Predict(sample)`。":
        "The examples below use 2D numeric features and integer class labels (`0`, `1`, `2`), consistent with `Examples/MachineLearning_example` and `TESTS/ML_module_test`. All classifiers implement `IClassifier<T>` with `Fit(x, y)` / `Predict(sample)`.",
    "The following example uses  MatrixOperations class中 Multiply 方法的示例，并在示例中加入了注释：":
        "The following example uses `MatrixOperations.Multiply` with comments:",
    "The following example uses  Quaternion struct中多个方法的示例，并在示例中加入了注释：":
        "The following example uses several `Quaternion` methods with comments:",
}

# Parameter / doc phrase replacements (apply inside lines, longest first)
PHRASES = [
    ("当基的维度不匹配时抛出", "Thrown when basis dimensions do not match"),
    ("当矩阵 A 不是方阵或 A 的行数与向量 b 的维度不匹配时抛出",
     "Thrown when A is not square or dimensions of A and b do not match"),
    ("当矩阵的维度不兼容时抛出", "Thrown when matrix dimensions are incompatible"),
    ("当输入数组的长度小于 2 或第一个系数为零时抛出",
     "Thrown when coefficient array length < 2 or first coefficient is zero"),
    ("第一个二维数组", "First 2D array"),
    ("第二个二维数组", "Second 2D array"),
    ("第一个锯齿数组矩阵", "First jagged matrix"),
    ("第二个锯齿数组矩阵", "Second jagged matrix"),
    ("用于初始化张量的三维数组", "3D array used to initialize the tensor"),
    ("第一个轴", "First axis"),
    ("第二个轴", "Second axis"),
    ("要切片的轴", "Axis to slice along"),
    ("处理行为，默认为 `Behaviour.Replace`", "Processing behaviour; default `Behaviour.Replace`"),
    ("用于划分数据的 bin 数量，默认为 32", "Bin count for histogram; default 32"),
    ("列索引数组", "Column index array"),
    ("列掩码数组", "Column mask array"),
    ("是否递归获取所有维度的长度", "Whether to recurse into all dimensions"),
    ("存储结果的矩阵", "Matrix to store result"),
    ("目标矩阵", "Destination matrix"),
    ("目标采样率", "Target sample rate"),
    ("维度（1 或 2）", "Dimension (1 or 2)"),
    ("多个向量", "Multiple vectors"),
    ("结束列索引", "End column index"),
    ("结束行索引", "End row index"),
    ("FFT 执行模式，默认为 `FftVersion.Normal`", "FFT execution mode; default `FftVersion.Normal`"),
    ("可选的 FIR 滤波器", "Optional FIR filter"),
    ("是否只获取第一个满足条件的元素的索引", "Whether to return only the first matching index"),
    ("波形的频率", "Waveform frequency"),
    ("条件函数", "Predicate function"),
    ("是否在原向量上进行操作", "Whether to operate in place on the vector"),
    ("是否在原矩阵上进行转置", "Whether to transpose in place"),
    ("切片的索引", "Slice index"),
    ("索引列表", "Index list"),
    ("索引数组", "Index array"),
    ("初始估计误差协方差的平方根", "Square root of initial estimate error covariance"),
    ("所有元素的初始值", "Initial value for all elements"),
    ("核函数类型", "Kernel type"),
    ("用于确定是否更改元素的函数", "Function that decides whether to change elements"),
    ("多个二维数组", "Multiple 2D arrays"),
    ("多个锯齿数组", "Multiple jagged arrays"),
    ("是否获取每个维度的最大长度", "Whether to use max length per dimension"),
    ("要与当前四元数进行比较的对象", "Object to compare with this quaternion"),
    ("要与当前张量进行比较的对象", "Object to compare with this tensor"),
    ("新的维度顺序", "New dimension order"),
    ("滤波器阶数，默认为 15", "Filter order; default 15"),
    ("另一个张量", "Other tensor"),
    ("要减去的张量", "Tensor to subtract"),
    ("要加的张量", "Tensor to add"),
    ("是否假设数组是矩形的", "Whether to assume a rectangular array"),
    ("存储结果的数组", "Array to store result"),
    ("存储转置结果的矩阵", "Matrix to store transpose result"),
    ("是否重用内存", "Whether to reuse memory"),
    ("行索引数组", "Row index array"),
    ("行掩码数组", "Row mask array"),
    ("行向量", "Row vector"),
    ("标量值", "Scalar value"),
    ("要乘以的标量值", "Scalar multiplier"),
    ("波形类型", "Waveform shape"),
    ("实现 `ISingleThreadTimeDomainSignal` 的信号对象", "Signal implementing `ISingleThreadTimeDomainSignal`"),
    ("源列表", "Source list"),
    ("源向量", "Source vector"),
    ("源矩阵", "Source matrix"),
    ("源锯齿数组", "Source jagged array"),
    ("起始列索引", "Start column index"),
    ("起始行索引", "Start row index"),
    ("是否转置结果", "Whether to transpose the result"),
    ("用于填充张量的值", "Value to fill the tensor with"),
    ("要搜索的值", "Value to search for"),
    ("要设置的值", "Value to set"),
    ("子矩阵的值", "Submatrix values"),
    ("X 坐标（宽度）", "X coordinate (width)"),
    ("Y 坐标（高度）", "Y coordinate (height)"),
    ("Z 坐标（深度）", "Z coordinate (depth)"),
    ("可选的窗函数类型", "Optional window type"),
    ("W 分量", "W component"),
    ("X 分量", "X component"),
    ("Y 分量", "Y component"),
    ("Z 分量", "Z component"),
    ("第一个点", "First point"),
    ("第二个点", "Second point"),
    ("第一个输入向量", "First input vector"),
    ("第二个输入向量", "Second input vector"),
    ("第一个向量", "First vector"),
    ("第二个向量", "Second vector"),
    ("第一个四元数", "First quaternion"),
    ("第二个四元数", "Second quaternion"),
    ("第一个张量", "First tensor"),
    ("第二个张量", "Second tensor"),
    ("第一个锯齿数组", "First jagged array"),
    ("第二个锯齿数组", "Second jagged array"),
    ("第一个矩阵", "First matrix"),
    ("第二个矩阵", "Second matrix"),
    ("深度", "Depth"),
    ("高度", "Height"),
    ("宽度", "Width"),
    ("元素", "Element"),
    ("索引", "Index"),
    ("张量", "Tensor"),
    ("数组", "Array"),
    ("二维数组", "2D array"),
    ("锯齿数组", "Jagged array"),
    ("向量", "Vector"),
    ("矩阵", "Matrix"),
    ("标量", "Scalar"),
    ("参数:", "Parameters:"),
    ("返回值:", "Returns:"),
    ("异常:", "Exceptions:"),
    ("抛出", "thrown"),
    ("class的新实例", "class instance"),
    ("struct体", "struct"),
    (" 类", " class"),
    (" 结构", " struct"),
    (" 接口", " interface"),
    (" 枚举", " enum"),
    ("（见上文表格）", "(see table above)"),
    ("加法运算符", "Addition operator"),
    ("减法运算符", "Subtraction operator"),
    ("乘法运算符", "Multiplication operator"),
    ("除法运算符", "Division operator"),
    ("相等运算符", "Equality operator"),
    ("不相等运算符", "Inequality operator"),
    ("#### 1. 加法运算符", "#### 1. Addition operator"),
    ("#### 2. 减法运算符", "#### 2. Subtraction operator"),
    ("#### 3. 乘法运算符", "#### 3. Multiplication operator"),
    ("#### 4. 除法运算符", "#### 4. Division operator"),
    ("#### 4. 相等运算符", "#### 4. Equality operator"),
    ("#### 5. 不相等运算符", "#### 5. Inequality operator"),
    ("#### 5. 相等运算符", "#### 5. Equality operator"),
    ("#### 6. 不相等运算符", "#### 6. Inequality operator"),
    ("大矩阵", "Large matrices"),
    ("小矩阵", "Small matrices"),
    ("未收敛时回退到 k×k Jacobi SVD", "fallback to k×k Jacobi SVD when not converged"),
    ("列矩阵散射回 NHWC 梯度（累加）", "scatter column matrix back to NHWC gradient (accumulate)"),
    ("由薄 SVD 估计", "estimated from thin SVD"),
    ("与库内 batch 卷积一致的 padding 与输出尺寸", "padding and output size consistent with in-library batch convolution"),
    ("等批量操作", " and other batch operations"),
    ("大行数时并行", "parallel for large row counts"),
    ("展开为 (numPatches × patchSize) 列矩阵", "expand to (numPatches × patchSize) column matrix"),
    ("条件数是否超过阈值", "whether condition number exceeds threshold"),
    ("方阵是否在容差内对称", "whether square matrix is symmetric within tolerance"),
    ("伪逆 A⁺", "pseudoinverse A⁺"),
    ("由 U、Σ、Vᵀ 重构 A", "reconstruct A from U, Σ, Vᵀ"),
    ("特征向量在结果矩阵的**列**中，按特征值降序排列", "eigenvectors in **columns** of result matrix, sorted by eigenvalue descending"),
    ("形状与 `ElementCount`", "shape and `ElementCount`"),
    ("获取指定列的值", "Gets value at column index"),
    ("获取列数", "Gets column count"),
    ("点积", "dot product"),
    ("欧几里得范数", "Euclidean norm"),
    ("向量加法", "vector addition"),
    ("向量减法", "vector subtraction"),
    ("标量乘法", "scalar multiplication"),
    ("归一化", "normalization"),
    ("索引器 `[d0, d1, d2, d3]` 与 `GetLinearIndex`", "Indexer `[d0, d1, d2, d3]` and `GetLinearIndex`"),
    ("用于多变量输入场景，其 `MultiPredict` 属性类型为 `Func<DataRow<T>, T>`",
     "for multivariate input; `MultiPredict` has type `Func<DataRow<T>, T>`"),
    ("参数默认为 `OptimizationMode.SIMD`，仅支持 `float` 和 `double`。使用其他类型时请选择 `OptimizationMode.Normal`",
     "defaults to `OptimizationMode.SIMD` (`float`/`double` only). Use `OptimizationMode.Normal` for other types"),
    ("是一个用于一维标准卡尔曼滤波器的类", "is a 1D standard Kalman filter"),
    ("是一个用于二维标准卡尔曼滤波器的类", "is a 2D standard Kalman filter"),
    ("是一个用于一维无迹卡尔曼滤波器的类", "is a 1D unscented Kalman filter"),
    ("是一个静态类，提供了多种矩阵和数组操作的辅助方法", "is a static helper for matrix and array operations"),
    ("是一个静态类，提供了执行矩阵运算的静态方法", "is a static class of matrix operations"),
    ("是一个表示四元数的泛型结构，提供了四元数的基本操作和运算方法",
     "is a generic quaternion struct with basic operations"),
    ("是一个表示三维张量的类，提供了张量的基本操作和运算方法", "is a 3D tensor with basic operations"),
    ("是一个表示三维张量的泛型类，提供了张量的基本操作和运算方法", "is a generic 3D tensor with basic operations"),
    ("亦提供同名实例方法", "also provides instance methods"),
    ("提供对称矩阵特征分解与薄 SVD", "provides symmetric eigendecomposition and thin SVD"),
    ("是静态工具类。数学向量用", "is a static utility. Math vectors use"),
    ("不与 BCL 的", "avoiding confusion with BCL"),
    ("（SIMD 寄存器）混淆", "(SIMD registers)"),
    ("是一个泛型静态类，提供多种曲线拟合方法的统一入口。类型参数 `T` 约束为",
     "is a generic static unified curve-fitting entry point. `T` is constrained to"),
    ("enum定义了所有支持的曲线拟合方法", "enum defines all supported curve-fitting methods"),
    ("是一个只读结构体，表示一行多列的数据，用于多变量输入的拟合方法",
     "is a readonly struct for one multivariate data row"),
    ("表示曲线拟合的结果", "represents a curve fit result"),
    ("enum定义了拟合算法的优化模式", "enum defines fitting optimization modes"),
    ("是一个**只读结构体**（`readonly struct`），实现了 `IFrequencyDomain` interface，用于表示频域信号。该结构体封装了傅里叶变换的结果，包括原始信号、窗函数信息和计算得到的频域特征",
     "is a **readonly struct** implementing `IFrequencyDomain` for frequency-domain signals; wraps FFT results, window info, and computed features"),
    ("定义了频域分析的常用属性", "defines common frequency-domain analysis properties"),
    ("继承自 `IFrequencyDomainCharacteristics`，定义了完整的频域信号接口",
     "extends `IFrequencyDomainCharacteristics` with the full frequency-domain contract"),
    ("继承自 `ITimeDomainSignal`，支持运行时修改采样数据，包括追加、插入、删除和重采样操作",
     "extends `ITimeDomainSignal` with runtime mutation: append, insert, delete, resample"),
    ("继承自 `ITimeDomainSignal`，提供单线程场景下的采样数据访问",
     "extends `ITimeDomainSignal` with single-threaded sample access"),
    ("定义了时域信号的关键特征属性接口，用于分析信号在时域中的统计和结构特征",
     "defines time-domain feature properties for statistical/structural analysis"),
    ("继承自 `ITimeDomainCharacteristics`，定义了时域信号的基础契约",
     "extends `ITimeDomainCharacteristics` with the base time-domain contract"),
    ("是一个支持运行时安全修改采样数据的时域信号类，实现了 `IModifiableTimeDomainSignal` 和 `IDisposable` interface。提供锁保护的可写和只读视图、异步追加（通过 Channel）和批量刷新",
     "supports thread-safe runtime sample edits; implements `IModifiableTimeDomainSignal` and `IDisposable` with lock-protected views, async append (Channel), and batch flush"),
    ("是一个用于扩展信号类功能的静态类，提供了生成各种波形的方法",
     "static extensions to generate waveforms"),
    ("是一个**只读结构体**（`readonly struct`），实现了 `ITimeDomainSignal` 和 `ISingleThreadTimeDomainSignal` interface，用于表示信号的只读连续子段。时域特征属性采用延迟计算（`Lazy<T>`）",
     "is a **readonly struct** implementing `ITimeDomainSignal` and `ISingleThreadTimeDomainSignal` for readonly contiguous sub-segments; features use `Lazy<T>`"),
    ("是一个用于表示单线程时域信号的类，实现了 `ISingleThreadTimeDomainSignal`、`ICloneable<Signal>`、`IDisposable` 和 `IEquatable<Signal>` interface。内部使用 `POHBuffer<float>` 存储采样数据",
     "represents a single-threaded time-domain signal; implements `ISingleThreadTimeDomainSignal`, `ICloneable<Signal>`, `IDisposable`, `IEquatable<Signal>`; uses `POHBuffer<float>` internally"),
    ("| 属性 | class型 | 说明 |", "| Property | Type | Description |"),
    ("| 值 | 说明 |", "| Value | Description |"),
    ("| 方法 | 说明 | 模型 |", "| Method | Description | Model |"),
    ("| 方法 | 说明 |", "| Method | Description |"),
    ("与 `Signal` class类似，包含", "Similar to `Signal`; includes"),
    ("以及所有 `ITimeDomainCharacteristics` 属性", "and all `ITimeDomainCharacteristics` properties"),
    ("（返回 `LockedSamplesView`）", "(returns `LockedSamplesView`)"),
    ("运算符支持 Signal 与 float 及 Signal 与 Signal 之间的运算",
     "operators support `Signal` with `float` and `Signal` with `Signal`"),
    ("运算符支持 SignalSegment 与 float 及 SignalSegment 与 SignalSegment 之间的运算",
     "operators support `SignalSegment` with `float` and `SignalSegment` with `SignalSegment`"),
    ("所有 `ITimeDomainCharacteristics` 属性均可用，采用延迟计算 + SIMD 优化",
     "All `ITimeDomainCharacteristics` properties available with lazy evaluation + SIMD"),
    ("根据时间长度和采样率初始化信号", "Initializes signal from duration and sample rate"),
    ("根据时间长度和采样率初始化", "Initializes from duration and sample rate"),
    ("根据采样数量和采样率初始化信号", "Initializes signal from sample count and rate"),
    ("根据采样数量和采样率初始化", "Initializes from sample count and rate"),
    ("实际有效数据长度", "Actual valid data length"),
    ("信号幅度（最大值与最小值之差）", "Signal amplitude (max − min)"),
    ("根据相位计算的角速度数组", "Angular velocities from phase"),
    ("异步追加采样数据（可从其他线程调用）", "Async append samples (callable from other threads)"),
    ("异步追加采样数据（线程安全）", "Async append samples (thread-safe)"),
    ("平均能量（样本平方均值）", "Average energy (mean squared sample)"),
    ("平均功率（样本平方和 / 样本数）", "Average power (sum of squares / count)"),
    ("贝叶斯线性回归", "Bayesian linear regression"),
    ("带先验线性", "Linear with prior"),
    ("贝叶斯回归", "Bayesian regression"),
    ("频谱质心", "Spectral centroid"),
    ("余弦波", "Cosine wave"),
    ("三次样条插值", "Cubic spline interpolation"),
    ("分段三次多项式", "Piecewise cubic polynomial"),
    ("释放资源", "Release resources"),
    ("信号持续时间", "Signal duration"),
    ("与现有信号逐元素相加", "Element-wise add to existing signal"),
    ("与现有信号逐元素相除", "Element-wise divide with existing signal"),
    ("与现有信号逐元素相乘", "Element-wise multiply with existing signal"),
    ("与现有信号逐元素相减", "Element-wise subtract from existing signal"),
    ("归一化 Shannon 熵，值范围 [0, 1]", "Normalized Shannon entropy in [0, 1]"),
    ("指数回归", "Exponential regression"),
    ("刷新待追加的采样数据，返回实际追加的数量", "Flush pending appends; returns count appended"),
    ("刷新待追加的采样数据", "Flush pending appends"),
    ("频域信号的频率", "Frequency-domain signal frequency"),
    ("多变量 GPR", "Multivariate GPR"),
    ("高斯过程回归 (GPR)", "Gaussian process regression (GPR)"),
    ("核函数", "Kernel"),
    ("高斯过程回归", "Gaussian process regression"),
    ("在指定时间点处插入采样数据", "Insert samples at time"),
    ("在指定时间点处插入", "Insert at time"),
    ("在指定索引处插入采样数据", "Insert samples at index"),
    ("在指定索引处插入", "Insert at index"),
    ("信号长度", "Signal length"),
    ("线性回归", "Linear regression"),
    ("局部加权回归 (LOWESS)", "Locally weighted regression (LOWESS)"),
    ("局部线性", "Local linear"),
    ("局部加权回归", "Locally weighted regression"),
    ("对数回归", "Logarithmic regression"),
    ("频域信号的幅度数组", "Frequency-domain magnitude array"),
    ("均方误差 (MSE)", "Mean squared error (MSE)"),
    ("移动平均", "Moving average"),
    ("窗口平均", "Window average"),
    ("多变量神经网络回归", "Multivariate neural-network regression"),
    ("神经网络回归", "Neural-network regression"),
    ("多变量非线性回归", "Multivariate nonlinear regression"),
    ("非线性回归 (LM 算法)", "Nonlinear regression (LM)"),
    ("自定义 f(xVector, params)", "Custom f(xVector, params)"),
    ("自定义 f(x, params)", "Custom f(x, params)"),
    ("非线性回归", "Nonlinear regression"),
    ("使用标准托管代码，支持所有 `IFloatingPointIeee754<T>` class型",
     "Standard managed code for all `IFloatingPointIeee754<T>` types"),
    ("频域变换在时域信号中的偏移量", "FFT offset in time-domain signal"),
    ("拟合参数（斜率、截距或系数等）", "Fitted parameters (slope, intercept, coefficients, etc.)"),
    ("信号周期", "Signal period"),
    ("频域信号的相位数组", "Frequency-domain phase array"),
    ("粉红噪声", "Pink noise"),
    ("多项式回归", "Polynomial regression"),
    ("幂回归", "Power regression"),
    ("拟合后的预测函数", "Fitted prediction function"),
    ("移除指定时间段的采样数据", "Remove samples in time range"),
    ("移除指定时间段", "Remove time range"),
    ("移除指定索引开始的指定数量的采样数据", "Remove samples from index"),
    ("移除指定范围", "Remove range"),
    ("替换现有信号", "Replace existing signal"),
    ("重采样信号，返回 `ModifiableTimeDomainSignal`", "Resample; returns `ModifiableTimeDomainSignal`"),
    ("重采样", "Resample"),
    ("频率分辨率", "Frequency resolution"),
    ("FFT 变换结果的复数数组", "Complex FFT result array"),
    ("均方根值（平均能量的平方根）", "RMS (sqrt of average energy)"),
    ("使用 SIMD 优化，仅支持 `float` 和 `double`", "SIMD optimization (`float`/`double` only)"),
    ("锁保护的采样数据视图", "Lock-protected sample view"),
    ("信号采样数据", "Signal sample data"),
    ("采样率", "Sample rate"),
    ("锯齿波", "Sawtooth wave"),
    ("关联的原始时域信号", "Associated time-domain signal"),
    ("正弦波", "Sine wave"),
    ("正弦回归", "Sinusoidal regression"),
    ("方波", "Square wave"),
    ("支持向量回归", "Support vector regression"),
    ("总能量（等同于总功率）", "Total energy (same as total power)"),
    ("总功率（样本平方和）", "Total power (sum of squared samples)"),
    ("FFT 变换长度（2 的幂次）", "FFT length (power of 2)"),
    ("转换到频域", "Transform to frequency domain"),
    ("三角波", "Triangle wave"),
    ("白噪声", "White noise"),
    ("所使用的窗函数类型", "Window type applied"),
    ("过零率，值范围 [0, 1]", "Zero-crossing rate in [0, 1]"),
]
PHRASES.sort(key=lambda x: len(x[0]), reverse=True)

# Verb-line templates: Chinese suffix after partial English from pass1
def fix_doc_line(line: str) -> str:
    if line in EXACT_MAP:
        return EXACT_MAP[line]
    out = line
    for zh, en in PHRASES:
        out = out.replace(zh, en)
    # Fix hybrid Gets/Uses/Performs lines
    out = re.sub(r"  - Gets\s+", "  - Gets ", out)
    out = re.sub(r"  - Uses\s+", "  - Uses ", out)
    out = re.sub(r"  - Performs\s+", "  - Performs ", out)
    out = re.sub(r"  - Initializes\s+", "  - Initializes ", out)
    out = re.sub(r"  - Loads from\s+", "  - ", out)
    out = re.sub(r"  - Returns:\s*Returns:", "  - Returns:", out)
    out = re.sub(r"  - Returns:\s*返回", "  - Returns:", out)
    out = re.sub(r"返回一个元组，包含斜率和截距", "Tuple of slope and intercept", out)
    out = re.sub(r"返回计算得到的 x 值", "Computed x", out)
    out = re.sub(r"返回计算得到的 y 值", "Computed y", out)
    out = re.sub(r"  -  FFT", "  - Performs inverse FFT on", out)
    out = re.sub(r"  - FFT", "  - Performs inverse FFT on", out)
    # Common Gets patterns
    replacements = {
        "  - Gets  DBSCAN 的任务类型，支持聚类。": "  - Task type; supports clustering.",
        "  - Gets  K 均值聚类的任务类型，支持聚类。": "  - Task type; supports clustering.",
        "  - Gets  PCA 的任务类型，支持降维。": "  - Task type; supports dimensionality reduction.",
        "  - Gets FFT所使用的窗口类型。": "  - Gets the window type used for FFT.",
        "  - Gets FFT的长度。该值为2的N次方，通常会比 `ActualLength` 大。": "  - Gets FFT length (power of 2; usually > `ActualLength`).",
        "  - Gets 一元线性回归的任务类型，支持回归。": "  - Task type; supports regression.",
        "  - Gets 二维数组指定维度的长度。": "  - Gets length of the specified dimension of a 2D array.",
        "  - Gets 信号样本数组。": "  - Gets signal sample array.",
        "  - Gets 信号段的持续时间。": "  - Gets segment duration.",
        "  - Gets 信号段的起始位置。": "  - Gets segment start index.",
        "  - Gets 信号段的采样数据。": "  - Gets segment sample data.",
        "  - Gets 信号段的长度。": "  - Gets segment length.",
        "  - Gets 信号的周期（采样率的倒数）。": "  - Gets signal period (inverse of sample rate).",
        "  - Gets 信号的均方根值。": "  - Gets signal RMS.",
        "  - Gets 信号的幅度（最大值与最小值之差）。": "  - Gets signal amplitude (max − min).",
        "  - Gets 信号的平均功率（样本平方和 / 样本数）。": "  - Gets average power (sum of squares / count).",
        "  - Gets 信号的平均能量（样本平方均值）。": "  - Gets average energy (mean squared sample).",
        "  - Gets 信号的归一化 Shannon 熵。": "  - Gets normalized Shannon entropy.",
        "  - Gets 信号的总功率（样本平方和）。": "  - Gets total power (sum of squared samples).",
        "  - Gets 信号的总能量（样本平方和）。": "  - Gets total energy (sum of squared samples).",
        "  - Gets 信号的持续时间。": "  - Gets signal duration.",
        "  - Gets 信号的过零率。": "  - Gets zero-crossing rate.",
        "  - Gets 信号的采样率。": "  - Gets sample rate.",
        "  - Gets 信号的长度。": "  - Gets signal length.",
        "  - Gets 共同性数组。": "  - Gets communalities array.",
        "  - Gets 功率谱密度。": "  - Gets power spectral density.",
        "  - Gets 协方差矩阵。": "  - Gets covariance matrices.",
        "  - Gets 向量的行数。": "  - Gets vector row count.",
        "  - Gets 四元数的 W 分量。": "  - Gets quaternion W component.",
        "  - Gets 四元数的 X 分量。": "  - Gets quaternion X component.",
        "  - Gets 四元数的 Y 分量。": "  - Gets quaternion Y component.",
        "  - Gets 四元数的 Z 分量。": "  - Gets quaternion Z component.",
        "  - Gets 回归模型的回归系数。": "  - Gets regression coefficients.",
        "  - Gets 回归模型的截距。": "  - Gets regression intercept.",
        "  - Gets 因子分析的任务类型，支持降维。": "  - Task type; supports dimensionality reduction.",
        "  - Gets 因子载荷矩阵。": "  - Gets factor loadings matrix.",
        "  - Gets 多元线性回归的任务类型，支持回归。": "  - Task type; supports regression.",
        "  - Gets 层次聚类的任务类型，支持聚类。": "  - Task type; supports clustering.",
        "  - Gets 底层的固定缓冲区。": "  - Gets underlying pinned buffer.",
        "  - Gets 张量的值。": "  - Gets tensor values.",
        "  - Gets 张量的宽度。": "  - Gets tensor width.",
        "  - Gets 张量的广义转置。": "  - Gets generalized tensor transpose.",
        "  - Gets 张量的深度。": "  - Gets tensor depth.",
        "  - Gets 张量的高度。": "  - Gets tensor height.",
        "  - Gets 当前信号段的起始时间。": "  - Gets segment start time.",
        "  - Gets 或设置指定位置的元素。": "  - Gets or sets element at position.",
        "  - Gets 或设置指定坐标的值。": "  - Gets or sets value at coordinates.",
        "  - Gets 或设置指定索引处的采样值。": "  - Gets or sets sample at index.",
        "  - Gets 或设置此 Minkowski 距离的阶数 `p`。": "  - Gets or sets Minkowski order `p`.",
        "  - Gets 或设置每个维度的权重。默认值是一个全为 1 的向量。": "  - Gets or sets per-dimension weights (default all ones).",
        "  - Gets 所关联的实信号。": "  - Gets associated real signal.",
        "  - Gets 所属的父信号。": "  - Gets parent signal.",
        "  - Gets 所有满足条件的元素的索引。": "  - Gets indexes of all matching elements.",
        "  - Gets 指定列的元素。": "  - Gets elements of the specified column.",
        "  - Gets 指定行的元素。": "  - Gets elements of the specified row.",
        "  - Gets 支持向量机的任务类型，支持分类和回归。": "  - Task type; supports classification and regression.",
        "  - Gets 数组所有维度的总长度。": "  - Gets total length across all dimensions.",
        "  - Gets 数组每个维度的长度。": "  - Gets length of each dimension.",
        "  - Gets 期望最大化算法的任务类型，支持聚类。": "  - Task type; supports clustering.",
        "  - Gets 未补0的长度，也是实际有效数据的长度。": "  - Gets unpadded length (actual valid data length).",
        "  - Gets 权重。": "  - Gets weights.",
        "  - Gets 满足条件的元素数量。": "  - Gets count of matching elements.",
        "  - Gets 点的邻居。": "  - Gets neighbors of a point.",
        "  - Gets 特异性方差数组。": "  - Gets specific variances array.",
        "  - Gets 矢量量化的任务类型，支持聚类。": "  - Task type; supports clustering.",
        "  - Gets 矩阵的列数。": "  - Gets column count.",
        "  - Gets 矩阵的行数。": "  - Gets row count.",
        "  - Gets 矩阵的转置。": "  - Gets matrix transpose.",
        "  - Gets 码书。": "  - Gets codebook.",
        "  - Gets 第一个满足条件的元素的索引。": "  - Gets index of first matching element.",
        "  - Gets 第一个满足条件的元素的索引，如果没有找到则返回 null。": "  - Gets first matching index, or null.",
        "  - Gets 线性回归模型的截距。": "  - Gets linear regression intercept.",
        "  - Gets 线性回归模型的斜率。": "  - Gets linear regression slope.",
        "  - Gets 聚类中心（均值）。": "  - Gets cluster centers (means).",
        "  - Gets 行向量的转置。": "  - Gets transpose of row vector.",
        "  - Gets 解释的方差比例。": "  - Gets explained variance ratios.",
        "  - Gets 锯齿数组指定维度的长度。": "  - Gets length of specified dimension of jagged array.",
        "  - Gets 频域信号在原始数据中的起始量。": "  - Gets frequency-domain start offset in original data.",
        "  - Gets 频域信号，即FFT变换的结果。": "  - Gets frequency-domain signal (FFT result).",
        "  - Gets 频率分辨率。": "  - Gets frequency resolution.",
        "  - Gets 高斯混合模型的任务类型，支持聚类。": "  - Task type; supports clustering.",
    }
    if out in replacements:
        return replacements[out]
    return out


def process_file(path: Path) -> int:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    out_lines = [fix_doc_line(l) if re.search(r"[\u4e00-\u9fff]", l) else l for l in lines]
    new_text = "\n".join(out_lines) + ("\n" if text.endswith("\n") else "")
    path.write_text(new_text, encoding="utf-8", newline="\n")
    return len(re.findall(r"[\u4e00-\u9fff]", new_text))


def main():
    for name in FILES:
        remaining = process_file(EN / name)
        lines = len((EN / name).read_text(encoding="utf-8").splitlines())
        print(f"{name}: {lines} lines, {remaining} Chinese chars left")
    return 0


if __name__ == "__main__":
    sys.exit(main())
