#!/usr/bin/env python3
"""Translate Signal Processing wiki docs (Signals, Operations, Filters) zh -> en."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HANS = ROOT / "wiki_hans"
EN = ROOT / "wiki_en"

MAPPINGS = [
    (
        "Module_SignalProcessing_Signals_zh.md",
        "Module_SignalProcessing_Signals.md",
        "Signals",
    ),
    (
        "Module_SignalProcessing_Operations_zh.md",
        "Module_SignalProcessing_Operations.md",
        "Operations",
    ),
    (
        "Module_SignalProcessing_Filters_zh.md",
        "Module_SignalProcessing_Filters.md",
        "Filters",
    ),
]

LINK_REPLACEMENTS = [
    ("HOME_zh.md", "HOME.md"),
    ("Module_SignalProcessing_zh.md", "Module_SignalProcessing.md"),
    ("Module_SignalProcessing_Signals_zh.md", "Module_SignalProcessing_Signals.md"),
    ("Module_SignalProcessing_Operations_zh.md", "Module_SignalProcessing_Operations.md"),
    ("Module_SignalProcessing_Filters_zh.md", "Module_SignalProcessing_Filters.md"),
    ("Module_ComputingContext_zh.md", "Module_ComputingContext.md"),
    ("Module_GPU_Policy_zh.md", "Module_GPU_Policy.md"),
    ("Module_Extensions_FFTW_zh.md", "Module_Extensions_FFTW.md"),
]

BREADCRUMBS = {
    "Module_SignalProcessing_Signals_zh.md": (
        "Location: [Home](HOME.md) / [Signal processing](Module_SignalProcessing.md) / "
        "[Signals](Module_SignalProcessing_Signals.md)"
    ),
    "Module_SignalProcessing_Operations_zh.md": (
        "Location: [Home](HOME.md) / [Signal processing](Module_SignalProcessing.md) / "
        "[Operations](Module_SignalProcessing_Operations.md)"
    ),
    "Module_SignalProcessing_Filters_zh.md": (
        "Location: [Home](HOME.md) / [Signal processing](Module_SignalProcessing.md) / "
        "[Filters](Module_SignalProcessing_Filters.md)"
    ),
}

# Longest-first phrase replacements
PHRASES = [
    # Breadcrumbs handled separately
    ("当前位置 : [首页](HOME.md)/[信号处理模块](Module_SignalProcessing.md)/[信号定义和相关操作](Module_SignalProcessing_Signals.md)",
     BREADCRUMBS["Module_SignalProcessing_Signals_zh.md"]),
    ("当前位置 : [首页](HOME.md)/[信号处理模块](Module_SignalProcessing.md)/[常用操作](Module_SignalProcessing_Operations.md)",
     BREADCRUMBS["Module_SignalProcessing_Operations_zh.md"]),
    ("当前位置 : [首页](HOME.md)/[信号处理模块](Module_SignalProcessing.md)/[一维滤波器](Module_SignalProcessing_Filters.md)",
     BREADCRUMBS["Module_SignalProcessing_Filters_zh.md"]),
    ("> 当前位置 : [首页](HOME.md)/[信号处理模块](Module_SignalProcessing.md)/[音效处理](Module_SignalProcessing_Effects.md)",
     "Location: [Home](HOME.md) / [Signal processing](Module_SignalProcessing.md) / [Audio effects](Module_SignalProcessing_Effects.md)"),
    # Titles
    ("# 信号处理模块 - Signal Processing Module", "# Signal Processing Module"),
    ("## 信号定义和相关操作 - Signals", "## Signals"),
    ("## 常用操作 - Operations", "## Operations"),
    ("## 一维滤波器 - Filters", "## Filters"),
    ("## 音效处理 - Audio Effect", "## Audio Effects"),
    # Intro paragraphs
    ("`Vorcyc.Mathematics.SignalProcessing.Signals` 命名空间包含时域/频域信号定义与编辑工具。",
     "The `Vorcyc.Mathematics.SignalProcessing.Signals` namespace provides time-domain and frequency-domain signal definitions and editing utilities."),
    ("`Vorcyc.Mathematics.SignalProcessing.Operations` 命名空间包含多种常用的信号处理操作类，包括卷积操作类（如 `ComplexConvolver`、`Convolver`、`OlaBlockConvolver`、`OlsBlockConvolver`）、动态处理类（如 `DynamicsProcessor`）、包络跟随器类（如 `EnvelopeFollower`）、信号重建类（如 `GriffinLimReconstructor`）、谐波/打击乐分离器类（如 `HarmonicPercussiveSeparator`）、调制类（如 `Modulator`）、通用操作类（如 `Operation`）、重采样类（如 `Resampler`）、谱减法滤波类（如 `SpectralSubtractor`）和波形整形类（如 `WaveShaper`）。这些类提供了丰富的信号处理功能，适用于各种音频和信号处理需求。",
     "The `Vorcyc.Mathematics.SignalProcessing.Operations` namespace includes common signal-processing operations: convolution (`ComplexConvolver`, `Convolver`, `OlaBlockConvolver`, `OlsBlockConvolver`), dynamics (`DynamicsProcessor`), envelope following (`EnvelopeFollower`), reconstruction (`GriffinLimReconstructor`), harmonic/percussive separation (`HarmonicPercussiveSeparator`), modulation (`Modulator`), general utilities (`Operation`), resampling (`Resampler`), spectral subtraction (`SpectralSubtractor`), and waveshaping (`WaveShaper`). These types support a wide range of audio and signal-processing tasks."),
    ("`Vorcyc.Mathematics.SignalProcessing.Filters` 命名空间包含多种一维滤波器类，包括自适应滤波器（如 `LmfFilter`、`LmsFilter`、`NlmfFilter`、`NlmsFilter`、`RlsFilter` 等）、基础滤波器（如 `FilterChain`、`FirFilter`、`IirFilter`、`StereoFilter` 等）、贝塞尔滤波器、双二阶滤波器、巴特沃斯滤波器、切比雪夫滤波器、椭圆滤波器、FIR 滤波器设计器、单极滤波器、多相滤波器、梳状滤波器、直流去除滤波器、去加重滤波器、Hilbert 滤波器、中值滤波器、移动平均滤波器、预加重滤波器、RASTA 滤波器、Savitzky-Golay 滤波器、Thiran 滤波器和维纳滤波器。这些类提供了丰富的滤波功能，适用于各种信号处理需求。",
     "The `Vorcyc.Mathematics.SignalProcessing.Filters` namespace includes 1D filters: adaptive (`LmfFilter`, `LmsFilter`, `NlmfFilter`, `NlmsFilter`, `RlsFilter`, etc.), base types (`FilterChain`, `FirFilter`, `IirFilter`, `StereoFilter`, etc.), Bessel, biquad, Butterworth, Chebyshev, elliptic, FIR design (`Fda`), one-pole, polyphase, comb, DC removal, de-emphasis, Hilbert, median, moving average, pre-emphasis, RASTA, Savitzky–Golay, Thiran, and Wiener filters."),
    ("> **0.9 API 说明**：下列各类的 **首选重载均接受 `Signal`**（返回 `Signal` 或写入 `Signal.Samples`）。`Operation.Convolve`、`CrossCorrelate`、`BlockConvolve`、`Resample`、`TimeStretch`、`Envelope`、`FullRectify`、`HalfRectify`、`SpectralSubtract` 等均已提供 `Signal` 版本；`Convolver` / `Modulator` / `SpectralSubtractor` 内部使用 `ReadOnlySpan<float>` 零拷贝路径。文档中仍出现的 `DiscreteSignal` 签名表示旧 API，等价迁移为 `Signal` 即可（采样率改为 `float`）。",
     "> **0.9 API note**: Preferred overloads for the types below **accept `Signal`** (return `Signal` or write to `Signal.Samples`). `Operation.Convolve`, `CrossCorrelate`, `BlockConvolve`, `Resample`, `TimeStretch`, `Envelope`, `FullRectify`, `HalfRectify`, `SpectralSubtract`, and others have `Signal` versions; `Convolver` / `Modulator` / `SpectralSubtractor` use zero-copy `ReadOnlySpan<float>` internally. Remaining `DiscreteSignal` signatures are legacy; migrate to `Signal` (sample rate as `float`)."),
    ("**0.9 推荐 API**", "**0.9 recommended API**"),
    ("**兼容 / 过时**", "**Compatibility / obsolete**"),
    ("- `DiscreteSignal`、`DiscreteSignalExtensions`：仍可用，已 `[Obsolete]`；请改用 `Signal` / `SignalExtensions` 或 `DiscreteSignal.ToSignal()`。",
     "- `DiscreteSignal`, `DiscreteSignalExtensions`: still available, marked `[Obsolete]`; use `Signal` / `SignalExtensions` or `DiscreteSignal.ToSignal()`."),
    ("- 下文手册中保留 `DiscreteSignal` 章节供对照迁移；新代码请以 [Signal 类](#vorcycmathematicssignalprocessingsignalssignal-class) 为准。",
     "- The `DiscreteSignal` sections below are kept for migration reference; new code should use [Signal class](#vorcycmathematicssignalprocessingsignalssignal-class)."),
    # Namespace notes
    ("> 以下类型均位于命名空间 ：Vorcyc.Mathematics.SignalProcessing.Signals",
     "> All types below are in namespace: Vorcyc.Mathematics.SignalProcessing.Signals"),
    ("> 以下类型均位于命名空间 ：Vorcyc.Mathematics.SignalProcessing.Operations",
     "> All types below are in namespace: Vorcyc.Mathematics.SignalProcessing.Operations"),
    ("> 以下类型均位于命名空间 ：Vorcyc.Mathematics.SignalProcessing.Filters",
     "> All types below are in namespace: Vorcyc.Mathematics.SignalProcessing.Filters"),
    ("> 以下类型的根命名空间为 ：Vorcyc.Mathematics.SignalProcessing.Effects",
     "> Root namespace for the types below: Vorcyc.Mathematics.SignalProcessing.Effects"),
    ("> 以下类型均位于 Vorcyc.Mathematics.SignalProcessing.Signals.Builders 命名空间。",
     "> All types below are in namespace: Vorcyc.Mathematics.SignalProcessing.Signals.Builders"),
    ("> 以下类型均位于 Vorcyc.Mathematics.SignalProcessing.Operations.Convolution 命名空间。",
     "> All types below are in namespace: Vorcyc.Mathematics.SignalProcessing.Operations.Convolution"),
    ("> 以下类型均位于 Vorcyc.Mathematics.SignalProcessing.Filters.Adaptive 命名空间。",
     "> All types below are in namespace: Vorcyc.Mathematics.SignalProcessing.Filters.Adaptive"),
    # TOC & sections
    (":ledger:目录  ", ":ledger: Contents"),
    (":ledger:目录", ":ledger: Contents"),
    ("（**已过时**）", "(**obsolete**)"),
    ("### 构造与工厂", "### Constructors and factories"),
    ("### 主要属性", "### Main properties"),
    ("### 切片与拷贝", "### Slicing and copying"),
    ("### 频域与重采样", "### Frequency domain and resampling"),
    ("### 参数设置", "### Parameters"),
    ("### 枚举", "### Enums"),
    ("### 属性", "### Properties"),
    ("### 构造器", "### Constructors"),
    ("### 方法", "### Methods"),
    ("### 方法清单及说明", "### Methods"),
    ("### 索引器", "### Indexers"),
    ("### 隐式转换", "### Implicit conversions"),
    ("### 运算符", "### Operators"),
    ("### 代码示例", "### Code example"),
    ("### 描述", "### Description"),
    ("### 重写方法", "### Overrides"),
    ("### 要点", "### Notes"),
    ("无公开属性。", "No public properties."),
    ("无", "None"),
    # Table headers
    ("| 类型 | 说明 |", "| Type | Description |"),
    ("| 成员 | 说明 |", "| Member | Description |"),
    ("| 方法 | 说明 |", "| Method | Description |"),
    ("| 属性 | 类型 | 说明 |", "| Property | Type | Description |"),
    ("| 值 | 说明 |", "| Value | Description |"),
    # Signal intro table
    ("| `Signal` | 单线程时域实信号主类型：`float` 采样率、固定针脚缓冲、`Samples` 为 `Span<float>`，实现 `ISingleThreadTimeDomainSignal` |",
     "| `Signal` | Primary single-threaded real time-domain type: `float` sample rate, pinned buffer, `Samples` as `Span<float>`, implements `ISingleThreadTimeDomainSignal` |"),
    ("| `SignalSegment` | 对父 `Signal` 的零拷贝片段 `signal[start, length]`，用于帧级 SIMD 统计与特征 |",
     "| `SignalSegment` | Zero-copy slice `signal[start, length]` of parent `Signal`; frame-level SIMD statistics and features |"),
    ("| `SignalExtensions` | 信号编辑与帧统计扩展（替代已过时的 `DiscreteSignalExtensions`） |",
     "| `SignalExtensions` | Signal editing and frame statistics extensions (replaces obsolete `DiscreteSignalExtensions`) |"),
    ("| `ComplexDiscreteSignal` | 复数离散信号（卷积、频域运算等） |",
     "| `ComplexDiscreteSignal` | Complex discrete signal (convolution, frequency-domain ops, etc.) |"),
    # Signal class body
    ("`Signal` 是 **0.9** 起推荐的单线程实值时域信号类型。样本存放在 `POHBuffer<float>` 中，通过 `Samples` 属性以 `Span<float>` 暴露，修改后需调用 `NotifySamplesModified()` 以失效缓存的时域特征。",
     "`Signal` is the recommended single-threaded real time-domain type from **0.9**. Samples live in `POHBuffer<float>` and are exposed as `Span<float>` via `Samples`; call `NotifySamplesModified()` after edits to invalidate cached time-domain features."),
    ("| `Signal(int sampleCount, float samplingRate)` | 按样本数与采样率分配缓冲 |",
     "| `Signal(int sampleCount, float samplingRate)` | Allocate buffer by sample count and rate |"),
    ("| `Signal(TimeSpan duration, float samplingRate)` | 按时长与采样率分配缓冲 |",
     "| `Signal(TimeSpan duration, float samplingRate)` | Allocate buffer by duration and rate |"),
    ("| `Signal.Unit(int length, float samplingRate)` | 单位脉冲（首样本为 1） |",
     "| `Signal.Unit(int length, float samplingRate)` | Unit impulse (first sample is 1) |"),
    ("| `Signal.Constant(float value, int length, float samplingRate)` | 常数信号 |",
     "| `Signal.Constant(float value, int length, float samplingRate)` | Constant signal |"),
    ("| `Signal.FromCopy(ReadOnlySpan<float>, float)` | 从 span 拷贝构造 |",
     "| `Signal.FromCopy(ReadOnlySpan<float>, float)` | Construct from span copy |"),
    ("| `Signal.FromCopy(float[], float)` | 从数组拷贝构造 |",
     "| `Signal.FromCopy(float[], float)` | Construct from array copy |"),
    ("- `Samples`：`Span<float>` 可读写视图", "- `Samples`: read/write `Span<float>` view"),
    ("- 时域特征（带 SIMD 缓存）：`Amplitude`、`TotalPower`、`AveragePower`、`TotalEnergy`、`AverageEnergy`、`Rms`、`ZeroCrossingRate`、`Entropy`",
     "- Time-domain features (SIMD-cached): `Amplitude`, `TotalPower`, `AveragePower`, `TotalEnergy`, `AverageEnergy`, `Rms`, `ZeroCrossingRate`, `Entropy`"),
    ("- `this[int start, int length]` → `SignalSegment?` 零拷贝片段",
     "- `this[int start, int length]` → zero-copy `SignalSegment?`"),
    ("- `TransformToFrequencyDomain(ComputingContext?, WindowType?)` → `FrequencyDomain`（推荐）",
     "- `TransformToFrequencyDomain(ComputingContext?, WindowType?)` → `FrequencyDomain` (recommended)"),
    ("- `TransformToFrequencyDomain(WindowType?, FftVersion)` → `FrequencyDomain`（**已过时**，见 [ComputingContext](Module_ComputingContext.md)）",
     "- `TransformToFrequencyDomain(WindowType?, FftVersion)` → `FrequencyDomain` (**obsolete**; see [ComputingContext](Module_ComputingContext.md))"),
    ("- `ISingleThreadTimeDomainSignal.GetRms(context)` 等时域特征（可选执行策略）",
     "- `ISingleThreadTimeDomainSignal.GetRms(context)` and other time-domain features (optional execution policy)"),
    ("- `Resample(float destinationSamplingRate, FirFilter?, int order)` → 新 `Signal`",
     "- `Resample(float destinationSamplingRate, FirFilter?, int order)` → new `Signal`"),
    ("`+`、`-`、`*`、`/`（标量与同形状 `Signal` 逐样本运算，返回新 `Signal`）",
     "`+`, `-`, `*`, `/` (scalar and same-shape `Signal` element-wise ops; returns new `Signal`)"),
    ("只读结构体，表示父 `Signal` 上连续样本的零拷贝视图。实现 `ITimeDomainSignal` / `ISingleThreadTimeDomainSignal`，帧级 `Rms`、`AverageEnergy`、`ZeroCrossingRate`、`Entropy` 等通过 SIMD 延迟计算。",
     "Readonly struct: zero-copy view of contiguous samples on a parent `Signal`. Implements `ITimeDomainSignal` / `ISingleThreadTimeDomainSignal`; frame-level `Rms`, `AverageEnergy`, `ZeroCrossingRate`, `Entropy`, etc. are lazily computed with SIMD."),
    ("- 由 `signal[start, length]` 或 `signal[range]` 获得", "- Obtained via `signal[start, length]` or `signal[range]`"),
    ("- `Samples` 为指向父缓冲子区间的 `Span<float>`", "- `Samples` is a `Span<float>` into the parent buffer sub-range"),
    ("- 可独立调用 `TransformToFrequencyDomain`、`Resample`", "- Can call `TransformToFrequencyDomain`, `Resample` independently"),
    ("自 `DiscreteSignalExtensions` 迁移的静态扩展方法（**新代码请用本类**）。",
     "Static extensions migrated from `DiscreteSignalExtensions` (**use this class in new code**)."),
    ("| `First` / `Last` | 取前/后 n 个样本（新 `Signal`） |", "| `First` / `Last` | First/last n samples (new `Signal`) |"),
    ("| `Amplify` / `Attenuate` / `Reverse` | 原地增益/反转 |", "| `Amplify` / `Attenuate` / `Reverse` | In-place gain / reverse |"),
    ("| `NormalizeMax` | 按峰值归一化到 [-1, 1] |", "| `NormalizeMax` | Peak-normalize to [-1, 1] |"),
    ("| `Delay` | 延迟副本（正 delay 延长，负 delay 截断左移） |", "| `Delay` | Delayed copy (positive delay pads; negative delay truncates/shifts left) |"),
    ("| `Concatenate` / `Repeat` | 连接 / 重复 |", "| `Concatenate` / `Repeat` | Concatenate / repeat |"),
    ("| `Superimpose` / `SuperimposeMany` / `Subtract` | 叠加与相减（支持不等长广播） |",
     "| `Superimpose` / `SuperimposeMany` / `Subtract` | Superimpose and subtract (unequal-length broadcast) |"),
    ("| `FullRectify` / `HalfRectify` | 原地整流 |", "| `FullRectify` / `HalfRectify` | In-place rectification |"),
    ("| `FadeIn` / `FadeOut` / `FadeInFadeOut` | 线性淡入淡出（`double` 秒或 `TimeSpan`） |",
     "| `FadeIn` / `FadeOut` / `FadeInFadeOut` | Linear fade in/out (`double` seconds or `TimeSpan`) |"),
    ("| `Crossfade` | 两信号交叉淡化 |", "| `Crossfade` | Crossfade two signals |"),
    ("| `ToComplex` | 转为 `ComplexDiscreteSignal`（虚部为零） |", "| `ToComplex` | Convert to `ComplexDiscreteSignal` (zero imaginary part) |"),
    ("| `Energy` / `Rms` / `ZeroCrossingRate` / `Entropy` | 区间统计（`Signal` 或 `ReadOnlySpan<float>`） |",
     "| `Energy` / `Rms` / `ZeroCrossingRate` / `Entropy` | Range statistics (`Signal` or `ReadOnlySpan<float>`) |"),
    # Common doc patterns
    ("  - 参数:", "  - Parameters:"),
    ("  - 返回值:", "  - Returns:"),
    ("  - 异常:", "  - Exceptions:"),
    ("  - 枚举成员:", "  - Enum members:"),
    ("  - 获取", "  - Gets "),
    ("  - 返回", "  - Returns "),
    ("  - 计算", "  - Computes "),
    ("  - 使用", "  - Uses "),
    ("  - 判断", "  - Determines whether "),
    ("  - 初始化", "  - Initializes "),
    ("  - 执行", "  - Performs "),
    ("  - 训练", "  - Trains "),
    ("  - 预测", "  - Predicts "),
    ("  - 创建", "  - Creates "),
    ("  - 扩展", "  - Expands "),
    ("  - 更新", "  - Updates "),
    ("  - 估计", "  - Estimates "),
    ("  - 添加", "  - Adds "),
    ("  - 保存", "  - Saves "),
    ("  - 加载", "  - Loads "),
    ("  - 将", "  - "),
    ("  - 对", "  - "),
    ("  - 根据", "  - "),
    ("  - 从", "  - Loads from "),
    ("  - 在", "  - "),
    ("  - 沿", "  - Along "),
    ("  - 用", "  - Fills "),
    ("  - 水平", "  - Horizontally "),
    ("  - 垂直", "  - Vertically "),
    ("  - 查找", "  - Finds "),
    ("  - 找到", "  - Finds "),
    ("  - 搜索", "  - Searches "),
    ("  - 生成", "  - Generates "),
    ("  - 学习", "  - Learns "),
    ("  - 固定为", "  - Fixed to "),
    ("  - 可选", "  - Optional "),
    ("  - 归一化", "  - Normalizes "),
    ("  - 克隆", "  - Clones "),
    ("  - 写入", "  - Writes "),
    ("  - 读取", "  - Reads "),
    ("  - 重置", "  - Resets "),
    ("  - 设置", "  - Sets "),
    ("  - 构造", "  - Constructs "),
    ("  - 滤波", "  - Filters "),
    ("  - 应用", "  - Applies "),
    ("  - 设计", "  - Designs "),
    ("  - 当", "  - Thrown when "),
    ("以下是一个使用", "The following example uses "),
    (" 类中多个方法的示例，并在示例中加入了注释：", " with comments:"),
    (" 类中 Transform 方法的示例，并在示例中加入了注释：", " `Transform` with comments:"),
    ("可以在 `SignalBuilder.SetParameter(string, double)` 方法中设置以下参数：",
     "Set the following via `SignalBuilder.SetParameter(string, double)`:"),
    ("#### 1. 构造函数", "#### 1. Constructor"),
    ("#### 1. 构造器", "#### 1. Constructor"),
    (" 构造函数", " constructor"),
    ("  - 表示 ", "  - Represents "),
    ("  - 构造 ", "  - Constructs "),
    ("  - 继承", "  - Inherits "),
    ("  - 实现", "  - Implements "),
    ("是一个用于", "is used for "),
    ("是一个用于实现", "implements "),
    ("是一个用于表示", "represents "),
    ("是一个用于构建", "builds "),
    ("是一个用于生成", "generates "),
    ("是一个静态类", "is a static class"),
    ("是一个抽象类", "is an abstract class"),
    ("是一个枚举", "is an enum"),
    ("继承了", "inherits "),
    ("，继承了", ", inherits "),
    ("并实现了", " and implements "),
    ("类。", " class."),
    ("结构体。", " struct."),
    ("接口。", " interface."),
    ("枚举。", " enum."),
    ("的类", " class"),
    ("的类，", " class, "),
    ("的静态类", " static class"),
    ("的抽象类", " abstract class"),
    ("的枚举", " enum"),
    ("的结构体", " struct"),
    ("的接口", " interface"),
    ("的扩展方法", " extension methods"),
    ("的实例。", " instance."),
    ("的新实例。", " instance."),
    ("实例。", " instance."),
    ("样本数", "sample count"),
    ("采样率", "sample rate"),
    ("采样数据", "sample data"),
    ("输入信号", "input signal"),
    ("输出信号", "output signal"),
    ("卷积核", "kernel"),
    ("卷积结果", "convolution result"),
    ("互相关结果", "cross-correlation result"),
    ("反卷积结果", "deconvolution result"),
    ("FFT 大小，默认为 0", "FFT size; default 0"),
    ("FFT 大小", "FFT size"),
    ("滤波器", "filter"),
    ("滤波器阶数", "filter order"),
    ("步长因子", "step size"),
    ("泄漏因子", "leakage factor"),
    ("自适应", "adaptive"),
    ("低通", "low-pass"),
    ("高通", "high-pass"),
    ("带通", "band-pass"),
    ("带阻", "band-stop"),
    ("截止频率", "cutoff frequency"),
    ("通带", "passband"),
    ("阻带", "stopband"),
    ("增益", "gain"),
    ("衰减", "attenuation"),
    ("攻击阶段", "attack phase"),
    ("衰减阶段", "decay phase"),
    ("持续阶段", "sustain phase"),
    ("释放阶段", "release phase"),
    ("攻击", "attack"),
    ("衰减", "decay"),
    ("持续", "sustain"),
    ("释放", "release"),
    ("均值，默认值为", "mean; default"),
    ("标准差，默认值为", "standard deviation; default"),
    ("默认值为", "default"),
    ("生成的样本", "generated sample"),
    ("生成的样本。", "generated sample."),
    ("生成的 `DiscreteSignal` 对象", "generated `DiscreteSignal`"),
    ("生成的 `Signal` 对象", "generated `Signal`"),
    ("重置样本生成器", "resets the sample generator"),
    ("设置信号的采样率", "sets signal sample rate"),
    ("设置采样率", "sets sample rate"),
    ("设置采样率后的 SignalBuilder 实例", "`SignalBuilder` after setting sample rate"),
    ("生成新的样本", "generates the next sample"),
    ("生成信号，通过逐个生成所有样本", "generates signal sample by sample"),
    ("下限幅度", "lower amplitude"),
    ("上限幅度", "upper amplitude"),
    ("起始频率", "start frequency"),
    ("结束频率", "end frequency"),
    ("持续时间（秒）", "duration (seconds)"),
    ("持续时间", "duration"),
    ("样本数表示", "in samples"),
    ("以样本数表示", "in sample count"),
    ("以秒为单位", "in seconds"),
    ("逐样本运算", "element-wise"),
    ("逐元素", "element-wise"),
    ("零拷贝", "zero-copy"),
    ("已过时", "obsolete"),
    ("推荐", "recommended"),
    ("见上文表格", "see table above"),
    ("见", "see"),
    ("命名空间", "namespace"),
    ("目录", "Contents"),
    ("说明", "Description"),
    ("方法", "Method"),
    ("属性", "Property"),
    ("类型", "Type"),
    ("成员", "Member"),
    ("值", "Value"),
    ("参数", "parameter"),
    ("返回值", "return value"),
    ("异常", "exception"),
    ("抛出", "thrown"),
    ("获取", "Gets"),
    ("返回", "Returns"),
    ("计算", "Computes"),
    ("使用", "Uses"),
    ("执行", "Performs"),
    ("初始化", "Initializes"),
    ("创建", "Creates"),
    ("生成", "Generates"),
    ("设置", "Sets"),
    ("重置", "Resets"),
    ("输入", "input"),
    ("输出", "output"),
    ("信号", "signal"),
    ("样本", "sample"),
    ("频率", "frequency"),
    ("幅度", "amplitude"),
    ("相位", "phase"),
    ("功率", "power"),
    ("能量", "energy"),
    ("窗函数", "window"),
    ("卷积", "convolution"),
    ("互相关", "cross-correlation"),
    ("反卷积", "deconvolution"),
    ("重采样", "resample"),
    ("整流", "rectification"),
    ("淡入淡出", "fade"),
    ("叠加", "superimpose"),
    ("连接", "concatenate"),
    ("反转", "reverse"),
    ("延迟", "delay"),
    ("调制", "modulation"),
    ("解调", "demodulation"),
    ("包络", "envelope"),
    ("谐波", "harmonic"),
    ("打击乐", "percussive"),
    ("分离", "separation"),
    ("重建", "reconstruction"),
    ("动态处理", "dynamics processing"),
    ("波形整形", "waveshaping"),
    ("谱减法", "spectral subtraction"),
    ("维纳滤波", "Wiener filtering"),
    ("移动平均", "moving average"),
    ("中值滤波", "median filtering"),
    ("梳状滤波", "comb filtering"),
    ("预加重", "pre-emphasis"),
    ("去加重", "de-emphasis"),
    ("直流去除", "DC removal"),
    ("双二阶", "biquad"),
    ("巴特沃斯", "Butterworth"),
    ("切比雪夫", "Chebyshev"),
    ("椭圆", "elliptic"),
    ("贝塞尔", "Bessel"),
    ("单极", "one-pole"),
    ("多相", "polyphase"),
    ("最小均方", "least mean square"),
    ("最小均方四次", "least-mean-fourth"),
    ("归一化", "normalized"),
    ("归一化最小均方", "normalized least mean square"),
    ("递归最小二乘", "recursive least squares"),
    ("符号", "sign"),
    ("可变步长", "variable step"),
    ("传递函数", "transfer function"),
    ("初始条件", "initial conditions"),
    ("群延迟", "group delay"),
    ("阶数", "order"),
    ("带宽", "bandwidth"),
    ("品质因数", "Q factor"),
    ("纹波", "ripple"),
    ("阻带衰减", "stopband attenuation"),
    ("通带增益", "passband gain"),
    ("原型", "prototype"),
    ("设计", "design"),
    ("应用滤波", "apply filter"),
    ("处理样本", "process sample"),
    ("处理信号", "process signal"),
    ("在线滤波", "online filtering"),
    ("离线滤波", "offline filtering"),
    ("块卷积", "block convolution"),
    ("重叠相加", "overlap-add"),
    ("重叠保留", "overlap-save"),
    ("时域拉伸", "time stretch"),
    ("时间拉伸", "time stretch"),
    ("音高变换", "pitch shift"),
    (" Griffin-Lim", " Griffin–Lim"),
    ("Griffin-Lim", "Griffin–Lim"),
    ("啁啾", "chirp"),
    ("加性白高斯噪声", "additive white Gaussian noise"),
    ("白高斯噪声", "white Gaussian noise"),
    ("粉红噪声", "pink noise"),
    ("红噪声", "red noise"),
    ("白噪声", "white noise"),
    ("Perlin 噪声", "Perlin noise"),
    ("正弦波", "sine wave"),
    ("余弦波", "cosine wave"),
    ("方波", "square wave"),
    ("锯齿波", "sawtooth wave"),
    ("三角波", "triangle wave"),
    ("脉冲波", "pulse wave"),
    ("包络", "envelope"),
    ("波形表", "wavetable"),
    ("Karplus-Strong", "Karplus–Strong"),
    ("Pad 合成", "pad synthesis"),
    ("淡入", "fade in"),
    ("淡出", "fade out"),
    ("交叉淡化", "crossfade"),
    ("实部", "real part"),
    ("虚部", "imaginary part"),
    ("复数", "complex"),
    ("离散信号", "discrete signal"),
    ("时域", "time domain"),
    ("频域", "frequency domain"),
    ("过零率", "zero-crossing rate"),
    ("熵", "entropy"),
    ("均方根", "RMS"),
    ("帧级", "frame-level"),
    ("特征", "features"),
    ("统计", "statistics"),
    ("区间", "range"),
    ("峰值", "peak"),
    ("常数", "constant"),
    ("单位脉冲", "unit impulse"),
    ("拷贝构造", "copy construction"),
    ("可读写视图", "read/write view"),
    ("只读结构体", "readonly struct"),
    ("只读", "readonly"),
    ("结构体", "struct"),
    ("扩展", "extensions"),
    ("静态", "static"),
    ("抽象", "abstract"),
    ("泛型", "generic"),
    ("枚举", "enum"),
    ("接口", "interface"),
    ("类", "class"),
    ("。", "."),
]

PHRASES.sort(key=lambda x: len(x[0]), reverse=True)


def translate_headers(text: str) -> str:
    text = re.sub(r"^(## .+?) 类\s*$", r"\1 class", text, flags=re.M)
    text = re.sub(r"^(## .+?) 结构\s*$", r"\1 struct", text, flags=re.M)
    text = re.sub(r"^(## .+?) 接口\s*$", r"\1 interface", text, flags=re.M)
    text = re.sub(r"^(## .+?) 枚举\s*$", r"\1 enum", text, flags=re.M)
    text = re.sub(r"\(#([^)]+)-类\)", lambda m: f"(#{m.group(1)}-class)", text)
    text = re.sub(r"\(#([^)]+)-结构\)", lambda m: f"(#{m.group(1)}-struct)", text)
    text = re.sub(r"\(#([^)]+)-接口\)", lambda m: f"(#{m.group(1)}-interface)", text)
    text = re.sub(r"\(#([^)]+)-枚举\)", lambda m: f"(#{m.group(1)}-enum)", text)
    text = re.sub(r" 类\)", " class)", text)
    text = re.sub(r" 结构\)", " struct)", text)
    text = re.sub(r" 枚举\)", " enum)", text)
    text = re.sub(r" 接口\)", " interface)", text)
    return text


def translate_text(text: str) -> str:
    for old, new in LINK_REPLACEMENTS:
        text = text.replace(old, new)
    for zh, en in PHRASES:
        text = text.replace(zh, en)
    text = translate_headers(text)
    # cleanup
    text = text.replace("..", ".")
    text = text.replace("class class", "class")
    text = text.replace("struct struct", "struct")
    text = text.replace("enum enum", "enum")
    text = text.replace("interface interface", "interface")
    text = re.sub(r"\s+\.", ".", text)
    return text


def translate_file(src: Path, dst: Path) -> tuple[int, int]:
    text = src.read_text(encoding="utf-8")
    out = translate_text(text)
    dst.write_text(out, encoding="utf-8", newline="\n")
    chinese = len(re.findall(r"[\u4e00-\u9fff]", out))
    return len(out.splitlines()), chinese


def main():
    for src_name, dst_name, _ in MAPPINGS:
        lines, chinese = translate_file(HANS / src_name, EN / dst_name)
        print(f"{dst_name}: {lines} lines, {chinese} Chinese chars remaining")
    return 0


if __name__ == "__main__":
    sys.exit(main())
