#!/usr/bin/env python3
"""Translate Chinese wiki module docs to English (Batch C)."""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HANS = ROOT / "wiki_hans"
EN = ROOT / "wiki_en"

MAPPINGS = [
    ("Module_MachineLearning_zh.md", "Module_MachineLearning.md", "Machine learning"),
    ("Module_LinearAlgebra_zh.md", "Module_LinearAlgebra.md", "Linear algebra"),
    ("Module_Experimental_zh.md", "Module_Experimental.md", "Experimental"),
]

# Longest-first phrase replacements (Chinese -> English)
PHRASES = [
    # Breadcrumbs & titles
    ("当前位置 : [首页](HOME_zh.md)/[机器学习模块](Module_MachineLearning_zh.md)",
     "Location: [Home](HOME.md) / [Machine learning](Module_MachineLearning.md)"),
    ("当前位置 : [首页](HOME_zh.md)/[线性代数模块](Module_LinearAlgebra_zh.md)",
     "Location: [Home](HOME.md) / [Linear algebra](Module_LinearAlgebra.md)"),
    ("当前位置 : [首页](HOME_zh.md)/[实验性模块](Module_Experimental_zh.md)",
     "Location: [Home](HOME.md) / [Experimental](Module_Experimental.md)"),
    ("# 机器学习模块 - Machine Learning Module", "# Machine learning module"),
    ("# 线性代数模块 - Linear Algebra Module", "# Linear algebra module"),
    ("# 实验性模块 - Experimental Module", "# Experimental module"),
    # Namespace notes
    ("> 以下所有类型都位于命名空间 : Vorcyc.Mathematics.MachineLearning",
     "> All types below are in the namespace `Vorcyc.Mathematics.MachineLearning`"),
    ("> 以下所有类型都位于命名空间 ：Vorcyc.Mathematics.LinearAlgebra",
     "> All types below are in the namespace `Vorcyc.Mathematics.LinearAlgebra`"),
    ("> 以下类型都位于 Vorcyc.Mathematics.Experimental.KalmanFilters 命名空间",
     "> All types below are in the namespace `Vorcyc.Mathematics.Experimental.KalmanFilters`"),
    ("> 以下类型都位于 Vorcyc.Mathematics.Experimental.Signals 命名空间",
     "> All types below are in the namespace `Vorcyc.Mathematics.Experimental.Signals`"),
    ("> 以下类型都位于 Vorcyc.Mathematics.Experimental.CurveFitting 命名空间",
     "> All types below are in the namespace `Vorcyc.Mathematics.Experimental.CurveFitting`"),
    # TOC
    (":ledger:目录", ":ledger: Contents"),
    ("[模块概览与新增 API](#模块概览与新增-api)", "[Module overview and new APIs](#module-overview-and-new-apis)"),
    ("[0.9 分类器完整示例](#09-分类器完整示例)", "[0.9 classifier walkthrough](#09-classifier-walkthrough)"),
    ("[距离度量类](#距离度量类)", "[Distance metric classes](#distance-metric-classes)"),
    # Section headers
    ("### 快速示例", "### Quick examples"),
    ("### 0.9 分类器完整示例", "### 0.9 classifier walkthrough"),
    ("### 属性", "### Properties"),
    ("### 构造器", "### Constructors"),
    ("### 方法", "### Methods"),
    ("### 方法清单及说明", "### Methods"),
    ("### 索引器", "### Indexers"),
    ("### 隐式转换", "### Implicit conversions"),
    ("### 运算符", "### Operators"),
    ("### 代码示例", "### Code example"),
    ("### 描述", "### Description"),
    ("# 距离度量类", "# Distance metric classes"),
    # Table headers (ML intro)
    ("| 子系统 | 命名空间 / 类型 | 说明 |", "| Subsystem | Namespace / types | Description |"),
    ("| 接口 | `IClassifier<T>`、`IRegressor<T>`、`IPreprocessor<T>` | 分类、回归、预处理统一契约 |",
     "| Interfaces | `IClassifier<T>`, `IRegressor<T>`, `IPreprocessor<T>` | Unified contracts for classification, regression, preprocessing |"),
    ("| 流水线 | `ClassificationPipeline<T>`、`RegressionPipeline<T>` | 预处理器链 + 模型 |",
     "| Pipelines | `ClassificationPipeline<T>`, `RegressionPipeline<T>` | Preprocessor chain + model |"),
    ("| 分类 | `Classfication.*`、`KnnClassifier`、`NumericDecisionTree`、`NumericRandomForest` | Softmax、KNN、逻辑回归、OvR、GNB、数值树/森林 |",
     "| Classification | `Classfication.*`, `KnnClassifier`, `NumericDecisionTree`, `NumericRandomForest` | Softmax, KNN, logistic regression, OvR, GNB, numeric trees/forests |"),
    ("| 集成 | `AdaBoostClassifier<T>`、`GradientBoostingClassifier<T>` | SAMME 决策桩、梯度提升多分类 |",
     "| Ensembles | `AdaBoostClassifier<T>`, `GradientBoostingClassifier<T>` | SAMME decision stumps, gradient boosting multiclass |"),
    ("| 回归 | `Regression.*`、`KnnRegressor` | 多元线性/岭回归、KNN 回归；MLR/MVR/KnnRegressor 实现 `IBatchRegressor` |",
     "| Regression | `Regression.*`, `KnnRegressor` | Multivariate linear/ridge regression, KNN regression; MLR/MVR/KnnRegressor implement `IBatchRegressor` |"),
    ("| 预处理 | `Preprocessing.*` | `StandardScaler`、`MinMaxScaler`、`LabelEncoder`、`OneHotEncoder` |",
     "| Preprocessing | `Preprocessing.*` | `StandardScaler`, `MinMaxScaler`, `LabelEncoder`, `OneHotEncoder` |"),
    ("| 评估 | `EvaluationMetrics`、`ClassificationMetrics` | MSE/RMSE/准确率、混淆矩阵、P/R/F1 |",
     "| Evaluation | `EvaluationMetrics`, `ClassificationMetrics` | MSE/RMSE/accuracy, confusion matrix, P/R/F1 |"),
    ("| 工具 | `DataSplit`、`CrossValidation`、`GridSearch`、`ModelBatchExtensions`、`IBatchClassifier` / `IBatchRegressor` | 划分、K 折 CV、网格搜索、批量预测 |",
     "| Utilities | `DataSplit`, `CrossValidation`, `GridSearch`, `ModelBatchExtensions`, `IBatchClassifier` / `IBatchRegressor` | Split, K-fold CV, grid search, batch prediction |"),
    ("| 降维 | `DimensionalityReduction.LDA` | 线性判别分析 |",
     "| Dimensionality reduction | `DimensionalityReduction.LDA` | Linear discriminant analysis |"),
    ("| 序列化 | `Serialization.ModelJsonPersistence` | Scaler / Softmax JSON 持久化 |",
     "| Serialization | `Serialization.ModelJsonPersistence` | Scaler / Softmax JSON persistence |"),
    # ML intro paragraph
    ("`Vorcyc.Mathematics.MachineLearning` 命名空间包含多种机器学习算法和工具类，包括数值决策树/随机森林、K 最近邻（`KnnClassifier` / `KNN`）、多元线性回归、多项式回归、岭回归、简单线性回归、支持向量机、高斯朴素贝叶斯、DBSCAN 聚类、期望最大化、高斯混合模型、层次聚类、K 均值聚类、矢量量化、因子分析、主成分分析 (PCA)、t-SNE 降维算法等。此外，还包括多种距离度量类。**0.9** 起模块提供统一接口、流水线、数值特征分类器、集成学习与评估工具（见下表）；可运行示例见 `Examples/MachineLearning_example/`。",
     "The `Vorcyc.Mathematics.MachineLearning` namespace includes many machine learning algorithms and utilities: numeric decision trees/random forests, K-nearest neighbors (`KnnClassifier` / `KNN`), multiple linear regression, polynomial regression, ridge regression, simple linear regression, support vector machines, Gaussian naive Bayes, DBSCAN clustering, expectation maximization, Gaussian mixture models, hierarchical clustering, K-means clustering, vector quantization, factor analysis, principal component analysis (PCA), t-SNE dimensionality reduction, and more. It also provides many distance metric classes. **From 0.9**, the module adds unified interfaces, pipelines, numeric-feature classifiers, ensemble learning, and evaluation utilities (see table below). Runnable examples: `Examples/MachineLearning_example/`."),
    # LA intro
    ("`Vorcyc.Mathematics.LinearAlgebra` 命名空间包含多种线性代数类和结构，包括 `BasisTransformation`、`LinearEquationSolver`、`Matrix`、`Matrix<T>`、`MatrixDecomposition`、`MatrixDiagnostics`、`MatrixHelper`、`MatrixOperations`、`Quaternion`、`Tensor`、`Tensor<T>`、`Tensor4D<T>`、`TensorOps` 和 `VectorSpan`。数学向量以 `ReadOnlySpan<T>` / `Span<T>` / `T[]` 表示，由 `VectorSpan` 提供点积、范数等运算，避免与 BCL 的 `System.Numerics.Vector<T>`（SIMD）命名冲突。4 维数据由布局中性的 `Tensor4D<T>` 存储；深度学习模块中的 `BatchTensor<T>`（NHWC）在其上封装 batch 语义。",
     "The `Vorcyc.Mathematics.LinearAlgebra` namespace includes linear algebra types such as `BasisTransformation`, `LinearEquationSolver`, `Matrix`, `Matrix<T>`, `MatrixDecomposition`, `MatrixDiagnostics`, `MatrixHelper`, `MatrixOperations`, `Quaternion`, `Tensor`, `Tensor<T>`, `Tensor4D<T>`, `TensorOps`, and `VectorSpan`. Math vectors are represented as `ReadOnlySpan<T>` / `Span<T>` / `T[]`; `VectorSpan` provides dot products, norms, and related operations while avoiding naming clashes with BCL `System.Numerics.Vector<T>` (SIMD). 4D data is stored in layout-neutral `Tensor4D<T>`; the deep learning module's `BatchTensor<T>` (NHWC) wraps batch semantics on top."),
    # Experimental intro
    ("`Vorcyc.Mathematics.Experimental.KalmanFilters` 命名空间包含多种卡尔曼滤波器类，包括 `ExtendedKalmanFilter1D<T>`、`ExtendedKalmanFilter2D<T>`、`InformationFilter1D<T>`、`ParticleFilter1D<T>`、`SquareRootKalmanFilter1D<T>`、`StandardKalmanFilter1D<T>`、`StandardKalmanFilter2D<T>` 和 `UnscentedKalmanFilter1D<T>`。这些类提供了丰富的滤波功能，适用于一维和二维的扩展卡尔曼滤波、信息滤波、粒子滤波、平方根卡尔曼滤波、标准卡尔曼滤波和无迹卡尔曼滤波。",
     "The `Vorcyc.Mathematics.Experimental.KalmanFilters` namespace includes Kalman filter types: `ExtendedKalmanFilter1D<T>`, `ExtendedKalmanFilter2D<T>`, `InformationFilter1D<T>`, `ParticleFilter1D<T>`, `SquareRootKalmanFilter1D<T>`, `StandardKalmanFilter1D<T>`, `StandardKalmanFilter2D<T>`, and `UnscentedKalmanFilter1D<T>`. These provide filtering for 1D/2D extended Kalman, information, particle, square-root Kalman, standard Kalman, and unscented Kalman filters."),
    ("`Vorcyc.Mathematics.Experimental.Signals` 命名空间包含多种信号处理接口、类和结构体。`ITimeDomainCharacteristics` 接口定义了时域特征属性（周期、幅度、总功率、平均功率、总能量、平均能量、RMS、过零率、熵）。`ITimeDomainSignal` 接口继承自 `ITimeDomainCharacteristics`，定义时域信号的基础契约。`ISingleThreadTimeDomainSignal` 接口提供单线程场景下的采样数据访问和重采样。`IModifiableTimeDomainSignal` 接口扩展了信号修改能力（追加、插入、删除、重采样），支持异步追加。`Signal` 类实现 `ISingleThreadTimeDomainSignal`，用于表示单线程时域信号，包含信号样本和采样率，并提供频域变换、重采样等方法。`ModifiableTimeDomainSignal` 类实现 `IModifiableTimeDomainSignal`，支持运行时安全的采样修改，提供锁保护的读写视图和异步批量追加。`FrequencyDomain` 只读结构体用于表示频域信号，提供频率转换、逆变换等方法。`SignalSegment` 只读结构体用于表示信号段，提供延迟计算的时域特征和频域转换。`SignalGeneratingExtension` 类提供了生成各种波形的方法，如正弦波、余弦波、方波、锯齿波、三角波、白噪声和粉红噪声。`IFrequencyDomain` 和 `IFrequencyDomainCharacteristics` 接口定义了频域信号的属性和频谱特征。",
     "The `Vorcyc.Mathematics.Experimental.Signals` namespace includes signal-processing interfaces, classes, and structs. `ITimeDomainCharacteristics` defines time-domain feature properties (period, amplitude, total/average power, total/average energy, RMS, zero-crossing rate, entropy). `ITimeDomainSignal` extends `ITimeDomainCharacteristics` with the base time-domain signal contract. `ISingleThreadTimeDomainSignal` provides sample access and resampling for single-threaded use. `IModifiableTimeDomainSignal` adds mutation (append, insert, delete, resample) with async append. `Signal` implements `ISingleThreadTimeDomainSignal` for single-threaded signals with samples, sample rate, frequency transforms, and resampling. `ModifiableTimeDomainSignal` implements `IModifiableTimeDomainSignal` with thread-safe sample edits, lock-protected read/write views, and async batch append. `FrequencyDomain` is a readonly struct for frequency-domain signals (frequency conversion, inverse transform). `SignalSegment` is a readonly struct for signal segments with lazily computed time-domain features and frequency conversion. `SignalGeneratingExtension` generates waveforms (sine, cosine, square, sawtooth, triangle, white/pink noise). `IFrequencyDomain` and `IFrequencyDomainCharacteristics` define frequency-domain properties and spectral features."),
    ("`Vorcyc.Mathematics.Experimental.CurveFitting` 命名空间提供了多种曲线拟合方法，通过 `CurveFitter<T>` 静态类统一访问。支持线性回归、多项式回归、指数回归、对数回归、幂回归、正弦回归、三次样条插值、局部加权回归 (LOWESS)、移动平均、非线性回归（Levenberg-Marquardt）、高斯过程回归 (GPR)、神经网络回归和贝叶斯线性回归等方法。所有拟合方法返回 `FitResult<T>` 或 `MultiColumnFitResult<T>`，包含预测函数、拟合参数和均方误差。支持 SIMD 优化（`float` 和 `double`）以及标准托管代码两种模式。",
     "The `Vorcyc.Mathematics.Experimental.CurveFitting` namespace provides curve-fitting methods via the static `CurveFitter<T>` class: linear, polynomial, exponential, logarithmic, power, sinusoidal regression, cubic spline interpolation, LOWESS, moving average, nonlinear regression (Levenberg–Marquardt), Gaussian process regression (GPR), neural-network regression, and Bayesian linear regression. All methods return `FitResult<T>` or `MultiColumnFitResult<T>` with a prediction function, fitted parameters, and mean squared error. Supports SIMD-optimized (`float`/`double`) and standard managed modes."),
    # Common doc phrases
    ("无公开属性。", "No public properties."),
    ("  - 参数:", "  - Parameters:"),
    ("  - 返回值:", "  - Returns:"),
    ("  - 异常:", "  - Exceptions:"),
    ("  - 获取", "  - Gets "),
    ("  - 初始化", "  - Initializes "),
    ("  - 使用", "  - Uses "),
    ("  - 执行", "  - Performs "),
    ("  - 计算", "  - Computes "),
    ("  - 将", "  - "),
    ("  - 对", "  - "),
    ("  - 根据", "  - "),
    ("  - 训练", "  - Trains "),
    ("  - 预测", "  - Predicts "),
    ("  - 查找", "  - Finds "),
    ("  - 扩展", "  - Expands "),
    ("  - 分配", "  - Allocates "),
    ("  - 更新", "  - Updates "),
    ("  - 估计", "  - Estimates "),
    ("  - 保存", "  - Saves "),
    ("  - 从", "  - Loads from "),
    ("  - 添加", "  - Adds "),
    ("  - 固定为", "  - Fixed to "),
    ("  - 可选", "  - Optional "),
    ("  - 获取指定类型的核函数。", "  - Gets the kernel function for the specified type."),
    ("  - 线性核函数。", "  - Linear kernel function."),
    ("  - 多项式核函数。", "  - Polynomial kernel function."),
    ("  - 高斯核函数（RBF）。", "  - Gaussian (RBF) kernel function."),
    ("  - Sigmoid 核函数。", "  - Sigmoid kernel function."),
    ("以下是一个使用", "The following example uses "),
    (" 类中多个方法的示例，并在示例中加入了注释：", " with comments:"),
    (" 类中 Transform 方法的示例，并在示例中加入了注释：", " `Transform` with comments:"),
    (" 类中多个方法的示例，并在示例中加入了注释：", " with comments:"),
    ("  - 当", "  - Thrown when "),
    ("  - 第一个点。", "  - First point."),
    ("  - 第二个点。", "  - Second point."),
    ("  - 第一个输入向量。", "  - First input vector."),
    ("  - 第二个输入向量。", "  - Second input vector."),
    ("  - 核函数的计算结果。", "  - Kernel function result."),
    ("  - 核函数类型。", "  - Kernel function type."),
    ("  - 表示 `x` 和 `y` 之间距离的值。", "  - Distance between `x` and `y`."),
    ("  - 表示 `x` 和 `y` 之间相似度的值。", "  - Similarity between `x` and `y`."),
    ("  - 计算点 `x` 和 `y` 之间的距离。", "  - Computes the distance between points `x` and `y`."),
    ("  - 计算点 `x` 和 `y` 之间的相似度。", "  - Computes the similarity between points `x` and `y`."),
    ("  - 获取两个点之间的相似度。", "  - Gets the similarity between two points."),
    ("  - 表示 `x` 和 `y` 之间距离的双精度值。", "  - `double` distance between `x` and `y`."),
    ("  - 表示 `x` 和 `y` 之间距离的单精度值。", "  - `float` distance between `x` and `y`."),
    # Code block section titles in ML
    ("**分类流水线**", "**Classification pipeline**"),
    ("**回归流水线 + K 折交叉验证**", "**Regression pipeline + K-fold cross-validation**"),
    ("**AdaBoost / 梯度提升**", "**AdaBoost / gradient boosting**"),
    ("**数据划分**", "**Data split**"),
    ("**数值决策树 / 随机森林**", "**Numeric decision tree / random forest**"),
    ("**高斯朴素贝叶斯 / KNN**", "**Gaussian naive Bayes / KNN**"),
    ("**Softmax / 逻辑回归 / One-vs-Rest**", "**Softmax / logistic regression / one-vs-rest**"),
    ("**评估指标**", "**Evaluation metrics**"),
    ("**K 折交叉验证**", "**K-fold cross-validation**"),
    ("**网格搜索（超参数）**", "**Grid search (hyperparameters)**"),
    ("**JSON 持久化（Scaler + Softmax）**", "**JSON persistence (scaler + Softmax)**"),
    ("**线性判别分析（LDA）**", "**Linear discriminant analysis (LDA)**"),
    # Code comments
    ("// x: [样本数, 特征数]，y: 整数类别", "// x: [samples, features], y: integer class labels"),
    ("// 各类别后验概率（字典：类别 → 概率）", "// Per-class posterior probabilities (class → probability)"),
    ("// 二分类（标签须为 0 或 1）", "// Binary classification (labels must be 0 or 1)"),
    ("// 多分类：内部为每个类别训练一个二分类器", "// Multiclass: trains one binary classifier per class"),
    ("// 批量预测（实现 IBatchClassifier 的模型走优化路径：树/森林、GNB、KNN、Softmax、Logistic、OvR、流水线等）",
     "// Batch prediction (IBatchClassifier models use optimized paths: trees/forests, GNB, KNN, Softmax, logistic, OvR, pipelines, etc.)"),
    ("// 或：var predictions = ModelBatchExtensions.PredictBatch(anyClassifier, xTest);", "// Or: var predictions = ModelBatchExtensions.PredictBatch(anyClassifier, xTest);"),
    ("// 用最佳超参在全量数据上重训", "// Retrain on full data with best hyperparameters"),
    ("// 加载后推理", "// Inference after load"),
    ("var projected = lda.Transform([2.1, 1.8]); // 降维后的特征", "var projected = lda.Transform([2.1, 1.8]); // reduced features"),
    ("# 运行完整分类演示（默认）", "# Run full classification demo (default)"),
    ("# 回归流水线演示", "# Regression pipeline demo"),
    ('Console.WriteLine($"准确率: {cv.MeanAccuracy:P1} ± {cv.StdAccuracy:P1}");',
     'Console.WriteLine($"Accuracy: {cv.MeanAccuracy:P1} ± {cv.StdAccuracy:P1}");'),
    # Class descriptions - ML
    ("`KNN<T>` 用于增量式 K 近邻**回归**（`Add` / `Regress` / `RegressBatch`）；矩阵训练请使用 `KnnRegressor<T>`（`IRegressor` + `IBatchRegressor`）。分类请使用 `KnnClassifier<T>`。",
     "`KNN<T>` is for incremental K-nearest-neighbor **regression** (`Add` / `Regress` / `RegressBatch`); for matrix training use `KnnRegressor<T>` (`IRegressor` + `IBatchRegressor`). For classification use `KnnClassifier<T>`."),
    ("  - 添加回归样本。", "  - Adds a regression sample."),
    ("  - 对特征向量进行 K 近邻回归；可选距离加权平均。", "  - KNN regression on a feature vector; optional distance weighting."),
    ("  - Fixed to `MachineLearningTask.Regression`。", "  - Fixed to `MachineLearningTask.Regression`."),
    ("  - Initializes KNN 类的新实例。", "  - Initializes a new `KNN` instance."),
    ("Vorcyc.Mathematics.MachineLearning.MultipleLinearRegression&lt;T> 是一个用于对数据集进行多元线性回归的类。正规方程在正定情形下优先使用 Cholesky 分解求解（`LinearEquationSolver.CholeskySolve`），否则回退 LU。",
     "`MultipleLinearRegression<T>` fits multivariate linear regression. The normal equations use Cholesky (`LinearEquationSolver.CholeskySolve`) when positive definite, otherwise LU."),
    ("  - Gets 回归模型的回归系数。", "  - Gets regression coefficients."),
    ("  - Gets 回归模型的截距。", "  - Gets the intercept."),
    ("  - Gets 多元线性回归的任务类型，支持回归。", "  - Task type; supports regression."),
    ("  - 学习多元线性回归模型的回归系数和截距。", "  - Learns coefficients and intercept."),
    ("    - `x`: 自变量矩阵。", "    - `x`: Independent variable matrix."),
    ("    - `y`: 因变量向量。", "    - `y`: Dependent variable vector."),
    ("  - 根据给定的自变量和回归系数预测因变量的值。", "  - Predicts the dependent variable from inputs and coefficients."),
    ("    - `x`: 自变量。", "    - `x`: Independent variables."),
    ("  - Returns: 预测的因变量值。", "  - Returns: Predicted dependent value."),
    ("        // 定义自变量矩阵", "        // Independent variable matrix"),
    ("        // 定义因变量向量", "        // Dependent variable vector"),
    ("        // 创建多元线性回归实例", "        // Create multiple linear regression instance"),
    ("        // 输出回归模型的截距和回归系数", "        // Print intercept and coefficients"),
    ("        // 预测新输入的因变量值", "        // Predict for new input"),
    ("Vorcyc.Mathematics.MachineLearning.SimpleLinearRegression&lt;T> 是一个用于一元线性回归的类。",
     "`SimpleLinearRegression<T>` performs simple (univariate) linear regression."),
    ("  - Gets 线性回归模型的斜率。", "  - Gets the slope."),
    ("  - Gets 线性回归模型的截距。", "  - Gets the intercept."),
    ("  - Gets 一元线性回归的任务类型，支持回归。", "  - Task type; supports regression."),
    ("  - 计算线性回归模型的斜率和截距。", "  - Computes slope and intercept."),
    ("    - `data`: 包含数据点的数组。", "    - `data`: Array of data points."),
    ("  - Returns: 返回一个元组，包含斜率和截距。", "  - Returns: Tuple of slope and intercept."),
    ("    - `x`: 自变量的数组。", "    - `x`: Independent variable array."),
    ("    - `y`: 因变量的数组。", "    - `y`: Dependent variable array."),
    ("  - 根据给定的 y 值、斜率和截距计算 x 值。", "  - Computes x from y, slope, and intercept."),
    ("    - `y`: 因变量的值。", "    - `y`: Dependent variable value."),
    ("  - Returns: 返回计算得到的 x 值。", "  - Returns: Computed x."),
    ("  - 根据给定的 x 值、斜率和截距计算 y 值。", "  - Computes y from x, slope, and intercept."),
    ("    - `x`: 自变量的值。", "    - `x`: Independent variable value."),
    ("  - Returns: 返回计算得到的 y 值。", "  - Returns: Computed y."),
    ("        // 定义数据点", "        // Data points"),
    ("        // 创建一元线性回归实例", "        // Create simple linear regression instance"),
    ("        // 输出回归模型的斜率和截距", "        // Print slope and intercept"),
    ("        // 预测新输入的 y 值", "        // Predict y for new x"),
    ("Vorcyc.Mathematics.MachineLearning.SupportVectorMachine&lt;TSelf> 是一个简单的线性支持向量机（SVM）实现，支持选择核函数。",
     "`SupportVectorMachine<TSelf>` is a simple linear SVM with selectable kernels."),
    ("  - Gets 支持向量机的任务类型，支持分类和回归。", "  - Task type; supports classification and regression."),
    ("  - Initializes SupportVectorMachine 类的新实例。", "  - Initializes a new `SupportVectorMachine` instance."),
    ("    - `featureCount`: 输入数据的特征数量。", "    - `featureCount`: Number of input features."),
    ("    - `learningRate`: 训练算法的学习率。为 null 时默认为 0.01。", "    - `learningRate`: Learning rate; default 0.01 when null."),
    ("    - `epochs`: 训练的轮数。", "    - `epochs`: Training epochs."),
    ("    - `kernelType`: 核函数类型。默认为线性核函数。", "    - `kernelType`: Kernel type; default linear."),
    ("  - Trains 使用提供的训练数据训练 SVM。", "  - Trains the SVM on the provided data."),
    ("    - `inputs`: 输入数据，每个元素是一个特征值数组。", "    - `inputs`: Training inputs (feature arrays)."),
    ("    - `outputs`: 与输入数据对应的输出标签。", "    - `outputs`: Output labels."),
    ("  - Predicts 给定输入数据的类别标签。", "  - Predicts the class label."),
    ("    - `input`: 输入数据，一个特征值数组。", "    - `input`: Feature array."),
    ("  - Returns: 预测的类别标签（1 或 -1）。", "  - Returns: Predicted label (1 or -1)."),
    ("  - 计算给定输入数据的原始预测值。", "  - Raw prediction score."),
    ("  - Returns: 原始预测值。", "  - Returns: Raw score."),
    ("        // 定义训练数据", "        // Training data"),
    ("        // 创建支持向量机实例", "        // Create SVM instance"),
    ("        // 训练支持向量机", "        // Train SVM"),
    ("        // 预测新输入的类别标签", "        // Predict label for new input"),
    # Clustering
    ("Vorcyc.Mathematics.MachineLearning.Clustering.DBSCAN&lt;T> 是一个用于二维平面点的 DBSCAN 聚类算法类。",
     "`DBSCAN<T>` performs DBSCAN clustering on 2D points."),
    ("  - Gets DBSCAN 的任务类型，支持聚类。", "  - Task type; supports clustering."),
    ("  - Uses 指定的点、邻域半径和最小点数初始化 DBSCAN 类的新实例。", "  - Initializes `DBSCAN` with points, neighborhood radius, and minimum points."),
    ("    - `points`: 要聚类的点。", "    - `points`: Points to cluster."),
    ("    - `eps`: 邻域半径。", "    - `eps`: Neighborhood radius."),
    ("    - `minPts`: 形成一个聚类的最小点数。", "    - `minPts`: Minimum points to form a cluster."),
    ("  - Performs DBSCAN 聚类。", "  - Runs DBSCAN clustering."),
    ("  - Returns: 聚类的列表，每个聚类是一个点的列表。", "  - Returns: List of clusters (each a list of points)."),
    ("  - Expands 聚类。", "  - Expands a cluster."),
    ("    - `point`: 当前点。", "    - `point`: Current point."),
    ("    - `neighbors`: 当前点的邻居。", "    - `neighbors`: Neighbors of the current point."),
    ("    - `cluster`: 当前聚类。", "    - `cluster`: Current cluster."),
    ("  - Gets 点的邻居。", "  - Gets neighbors of a point."),
    ("  - Returns: 邻居的列表。", "  - Returns: List of neighbors."),
    ("        // 定义点", "        // Points"),
    ("        // 创建 DBSCAN 实例", "        // Create DBSCAN instance"),
    ("        // 执行聚类", "        // Run clustering"),
    ("        // 输出聚类结果", "        // Print clusters"),
    ("Vorcyc.Mathematics.MachineLearning.Clustering.ExpectationMaximization&lt;T> 是一个用于实现期望最大化（EM）算法的类。",
     "`ExpectationMaximization<T>` implements the expectation-maximization (EM) algorithm."),
    ("  - Gets 聚类中心（均值）。", "  - Gets cluster centers (means)."),
    ("  - Gets 协方差矩阵。", "  - Gets covariance matrices."),
    ("  - Gets 权重。", "  - Gets mixture weights."),
    ("  - Gets 期望最大化算法的任务类型，支持聚类。", "  - Task type; supports clustering."),
    ("  - Initializes ExpectationMaximization 类的新实例。", "  - Initializes a new `ExpectationMaximization` instance."),
    ("    - `numClusters`: 聚类的数量。", "    - `numClusters`: Number of clusters."),
    ("  - 使用期望最大化算法拟合数据。", "  - Fits data with EM."),
    ("    - `data`: 要拟合的数据，表示为向量的列表。", "    - `data`: Data as a list of vectors."),
    ("        // 创建期望最大化实例", "        // Create EM instance"),
    ("        // 拟合数据", "        // Fit data"),
    ("        // 输出聚类中心", "        // Print cluster centers"),
    ("        // 输出协方差矩阵", "        // Print covariance matrices"),
    ("        // 输出权重", "        // Print weights"),
    ("Vorcyc.Mathematics.MachineLearning.Clustering.GMM&lt;T> 是一个用于实现高斯混合模型（GMM）的类。",
     "`GMM<T>` implements a Gaussian mixture model."),
    ("  - Gets 高斯混合模型的任务类型，支持聚类。", "  - Task type; supports clustering."),
    ("  - Initializes GMM 类的新实例。", "  - Initializes a new `GMM` instance."),
    ("    - `numComponents`: 高斯分布的数量。", "    - `numComponents`: Number of Gaussian components."),
    ("    - `maxIterations`: 最大迭代次数。", "    - `maxIterations`: Maximum iterations."),
    ("    - `tolerance`: 对数似然函数的收敛容差。", "    - `tolerance`: Log-likelihood convergence tolerance."),
    ("  - 使用高斯混合模型拟合数据。", "  - Fits data with GMM."),
    ("        // 创建高斯混合模型实例", "        // Create GMM instance"),
    ("Vorcyc.Mathematics.MachineLearning.Clustering.HierarchicalClustering&lt;T> 是一个用于二维平面点的层次聚类算法类。",
     "`HierarchicalClustering<T>` performs hierarchical clustering on 2D points."),
    ("  - Gets 层次聚类的任务类型，支持聚类。", "  - Task type; supports clustering."),
    ("  - Uses 指定的点初始化 HierarchicalClustering 类的新实例。", "  - Initializes with the given points."),
    ("  - 对点执行层次聚类，直到达到指定数量的聚类。", "  - Hierarchical clustering until `k` clusters remain."),
    ("    - `k`: 所需的聚类数量。", "    - `k`: Desired number of clusters."),
    ("  - Finds 最接近的两个聚类。", "  - Finds the two closest clusters."),
    ("  - Returns: 最接近的两个聚类的索引和它们之间的距离。", "  - Returns: Indices of the two closest clusters and their distance."),
    ("  - 计算两个聚类之间的平均连接距离。", "  - Average linkage distance between two clusters."),
    ("    - `cluster1`: 第一个聚类。", "    - `cluster1`: First cluster."),
    ("    - `cluster2`: 第二个聚类。", "    - `cluster2`: Second cluster."),
    ("  - Returns: 两个聚类之间的平均连接距离。", "  - Returns: Average linkage distance."),
    ("  - Computes 两个点之间的欧几里得距离。", "  - Euclidean distance between two points."),
    ("    - `a`: 第一个点。", "    - `a`: First point."),
    ("    - `b`: 第二个点。", "    - `b`: Second point."),
    ("  - Returns: 两个点之间的欧几里得距离。", "  - Returns: Euclidean distance."),
    ("        // 创建层次聚类实例", "        // Create hierarchical clustering instance"),
    ("Vorcyc.Mathematics.MachineLearning.Clustering.KMeansClusterer&lt;T> 是一个用于实现 K 均值聚类算法的类。",
     "`KMeansClusterer<T>` implements K-means clustering."),
    ("  - Gets K 均值聚类的任务类型，支持聚类。", "  - Task type; supports clustering."),
    ("  - Uses 指定的数据、聚类数量、最大迭代次数和收敛容忍度初始化 KMeansClusterer 类的新实例。",
     "  - Initializes `KMeansClusterer` with data, cluster count, max iterations, and tolerance."),
    ("    - `data`: 要聚类的数据。", "    - `data`: Data to cluster."),
    ("    - `numClusters`: 要创建的聚类数量。", "    - `numClusters`: Number of clusters."),
    ("    - `tolerance`: 收敛容忍度。", "    - `tolerance`: Convergence tolerance."),
    ("  - Performs K 均值聚类算法。", "  - Runs K-means."),
    ("  - Returns: 每个数据点的聚类分配。", "  - Returns: Cluster assignment per point."),
    ("  - 初始化聚类。", "  - Initializes cluster assignments."),
    ("    - `numData`: 数据的数量。", "    - `numData`: Number of data points."),
    ("  - Returns: 初始化的聚类分配。", "  - Returns: Initial assignments."),
    ("  - Allocates 二维数组的空间。", "  - Allocates a 2D array."),
    ("    - `numRows`: 行数。", "    - `numRows`: Row count."),
    ("    - `numCols`: 列数。", "    - `numCols`: Column count."),
    ("  - Returns: 分配的二维数组。", "  - Returns: Allocated 2D array."),
    ("  - Updates 质心（聚类中心）。", "  - Updates centroids."),
    ("  - Returns: 是否成功更新质心。", "  - Returns: Whether centroids changed."),
    ("  - Updates 聚类分配。", "  - Updates cluster assignments."),
    ("  - Returns: 是否成功更新聚类分配。", "  - Returns: Whether assignments changed."),
    ("  - Computes 两个向量之间的欧几里得距离。", "  - Euclidean distance between two vectors."),
    ("    - `vector1`: 第一个向量。", "    - `vector1`: First vector."),
    ("    - `vector2`: 第二个向量。", "    - `vector2`: Second vector."),
    ("  - Returns: 两个向量之间的欧几里得距离。", "  - Returns: Euclidean distance."),
    ("  - 找到数组中最小值的索引。", "  - Index of minimum value in an array."),
    ("    - `distances`: 表示距离的数组。", "    - `distances`: Distance array."),
    ("  - Returns: 最小值的索引。", "  - Returns: Index of minimum."),
    ("        // 创建 KMeansClusterer 实例", "        // Create KMeansClusterer instance"),
    ("Vorcyc.Mathematics.MachineLearning.Clustering.VectorQuantization&lt;T> 是一个用于实现矢量量化算法的类。",
     "`VectorQuantization<T>` implements vector quantization."),
    ("  - Gets 码书。", "  - Gets the codebook."),
    ("  - Gets 矢量量化的任务类型，支持聚类。", "  - Task type; supports clustering."),
    ("  - Initializes VectorQuantization 类的新实例。", "  - Initializes a new `VectorQuantization` instance."),
    ("    - `codebookSize`: 码书的大小。", "    - `codebookSize`: Codebook size."),
    ("    - `dimensions`: 矢量的维度。", "    - `dimensions`: Vector dimensions."),
    ("  - Trains 矢量量化模型。", "  - Trains the vector quantization model."),
    ("    - `data`: 训练数据，包含多个矢量。", "    - `data`: Training vectors."),
    ("  - Returns: 每次迭代的误差列表。", "  - Returns: Per-iteration error list."),
    ("  - 根据输入矢量找到最近的码矢量。", "  - Finds nearest code vector to input."),
    ("    - `vector`: 输入矢量。", "    - `vector`: Input vector."),
    ("  - Returns: 最近的码矢量。", "  - Returns: Nearest code vector."),
    ("  - Saves 码书保存到文件中。", "  - Saves codebook to file."),
    ("    - `filePath`: 文件路径。", "    - `filePath`: File path."),
    ("  - Loads from 文件中加载码书。", "  - Loads codebook from file."),
    ("        // 创建矢量量化实例", "        // Create vector quantization instance"),
    ("        // 训练模型", "        // Train model"),
    ("        // 输出训练误差", "        // Print training errors"),
    ("        // 预测新矢量", "        // Predict for new vector"),
    ("        // 保存码书", "        // Save codebook"),
    ("        // 加载码书", "        // Load codebook"),
    # Dimensionality reduction
    ("Vorcyc.Mathematics.MachineLearning.DimensionalityReduction.FactorAnalysis&lt;T> 是一个用于执行因子分析的类。",
     "`FactorAnalysis<T>` performs factor analysis."),
    ("  - Gets 因子载荷矩阵。", "  - Gets factor loadings matrix."),
    ("  - Gets 共同性数组。", "  - Gets communalities array."),
    ("  - Gets 特异性方差数组。", "  - Gets specific variances array."),
    ("  - Gets 因子分析的任务类型，支持降维。", "  - Task type; supports dimensionality reduction."),
    ("  - Initializes FactorAnalysis 类的新实例。", "  - Initializes a new `FactorAnalysis` instance."),
    ("  - Performs 因子分析。", "  - Runs factor analysis."),
    ("    - `data`: 数据矩阵，每行代表一个样本，每列代表一个变量。", "    - `data`: Data matrix (rows = samples, columns = variables)."),
    ("    - `numFactors`: 因子数量。", "    - `numFactors`: Number of factors."),
    ("        // 定义数据矩阵", "        // Data matrix"),
    ("        // 创建因子分析实例", "        // Create factor analysis instance"),
    ("        // 执行因子分析", "        // Run factor analysis"),
    ("        // 输出因子载荷矩阵", "        // Print factor loadings"),
    ("        // 输出共同性数组", "        // Print communalities"),
    ("        // 输出特异性方差数组", "        // Print specific variances"),
    ("Vorcyc.Mathematics.MachineLearning.DimensionalityReduction.PCA&lt;TSelf> 是一个用于降维和特征提取的主成分分析 (PCA) 类。",
     "`PCA<TSelf>` performs principal component analysis for dimensionality reduction and feature extraction."),
    ("  - Gets PCA 的任务类型，支持降维。", "  - Task type; supports dimensionality reduction."),
    ("  - Initializes PCA 类的新实例。", "  - Initializes a new `PCA` instance."),
    ("    - `data`: 输入数据集，每行是一个样本，每列是一个特征。", "    - `data`: Input data (rows = samples, columns = features)."),
    ("  - 将原始数据转换为主成分。", "  - Transforms data to principal components."),
    ("  - Returns: 转换后的主成分数据。", "  - Returns: Transformed principal components."),
    ("  - Gets 解释的方差比例。", "  - Gets explained variance ratios."),
    ("  - Returns: 解释的方差比例数组。", "  - Returns: Explained variance ratio array."),
    ("        // 创建 PCA 实例", "        // Create PCA instance"),
    ("        // 转换数据", "        // Transform data"),
    ("        // 输出转换后的数据", "        // Print transformed data"),
    ("        // 输出解释的方差比例", "        // Print explained variance ratios"),
    ("Vorcyc.Mathematics.MachineLearning.DimensionalityReduction.TSNE&lt;T> 是一个用于降维和数据可视化的 t-SNE 算法类。",
     "`TSNE<T>` implements t-SNE for dimensionality reduction and visualization."),
    ("  - Initializes TSNE 类的新实例。", "  - Initializes a new `TSNE` instance."),
    ("    - `perplexity`: 困惑度参数。", "    - `perplexity`: Perplexity."),
    ("    - `maxIter`: 最大迭代次数。", "    - `maxIter`: Maximum iterations."),
    ("    - `learningRate`: 学习率。", "    - `learningRate`: Learning rate."),
    ("  - Performs t-SNE 算法并返回降维后的矩阵。", "  - Runs t-SNE and returns reduced matrix."),
    ("    - `data`: 输入的高维数据矩阵。", "    - `data`: High-dimensional input matrix."),
    ("  - Returns: 降维后的矩阵。", "  - Returns: Reduced matrix."),
    ("        // 创建 t-SNE 实例", "        // Create t-SNE instance"),
    ("        // 执行 t-SNE 算法", "        // Run t-SNE"),
    ("        // 输出降维后的数据", "        // Print reduced data"),
    # Distance descriptions
    ("Angular 距离，或 Cosine 距离的正确度量版本。", "Angular distance; the proper metric version of cosine distance."),
    ("ArgMax 距离（L0 距离）。", "ArgMax distance (L0 distance)."),
    ("Bray-Curtis 距离。", "Bray–Curtis distance."),
    ("Canberra 距离。", "Canberra distance."),
    ("Chebyshev 距离。", "Chebyshev distance."),
    ("Cosine 距离。对于正确的距离度量，请参见 Angular 距离。", "Cosine distance. For a proper metric, see Angular distance."),
    ("Dice 不相似度。", "Dice dissimilarity."),
    ("欧几里得距离度量。", "Euclidean distance metric."),
    ("汉明距离。", "Hamming distance."),
    ("Hellinger 距离。", "Hellinger distance."),
    ("Jaccard（指数）距离。", "Jaccard (index) distance."),
    ("Kulczynski 不相似度。", "Kulczynski dissimilarity."),
    ("Levenshtein 距离。", "Levenshtein distance."),
    ("曼哈顿（也称为 Taxicab 或 L1）距离。", "Manhattan (taxicab or L1) distance."),
    ("Matching 不相似度。", "Matching dissimilarity."),
    ("Minkowski 距离是一个在范数向量空间中的度量，可以看作是欧几里得距离和曼哈顿距离的推广。",
     "Minkowski distance generalizes Euclidean and Manhattan distance in a normed vector space."),
    ("  - Gets 或设置此 Minkowski 距离的阶数 `p`。", "  - Gets or sets the order `p` of this Minkowski distance."),
    ("Pearson 相关性相似度。", "Pearson correlation similarity."),
    ("Rogers-Tanimoto 不相似度。", "Rogers–Tanimoto dissimilarity."),
    ("Russel-Rao 不相似度。", "Russel–Rao dissimilarity."),
    ("Sokal-Michener 不相似度。", "Sokal–Michener dissimilarity."),
    ("Sokal-Sneath 不相似度。", "Sokal–Sneath dissimilarity."),
    ("加权平方欧几里得距离和相似度。请注意，此距离不是度量，因为它不遵守三角不等式。",
     "Weighted squared Euclidean distance and similarity. Not a metric (violates triangle inequality)."),
    ("  - Gets 或设置每个维度的权重。默认值是一个全为 1 的向量。", "  - Gets or sets per-dimension weights; default is all ones."),
    ("  - 将 Weights 设置为指定维度的全 1 向量。", "  - Sets `Weights` to all ones for the given dimension count."),
    ("    - `dimensions`: 数据集中的维度（列）数。", "    - `dimensions`: Number of dimensions (columns)."),
    ("Yule 不相似度。", "Yule dissimilarity."),
    # Linear Algebra
    ("Vorcyc.Mathematics.LinearAlgebra.BasisTransformation 是一个静态类，提供基变换的方法。",
     "`BasisTransformation` is a static class for basis transformations."),
    ("  - 将向量从一个基变换到另一个基。", "  - Transforms a vector from one basis to another."),
    ("    - `vector`: 要变换的向量。", "    - `vector`: Vector to transform."),
    ("    - `fromBasis`: 原基。", "    - `fromBasis`: Source basis."),
    ("    - `toBasis`: 目标基。", "    - `toBasis`: Target basis."),
    ("  - Returns: 变换后的向量。", "  - Returns: Transformed vector."),
    ("  - Thrown when 基的维度不匹配时抛出。", "  - Thrown when basis dimensions do not match."),
    ("        // 定义向量和基矩阵", "        // Vector and basis matrices"),
    ("        // 进行基变换", "        // Transform basis"),
    ("        // 输出变换后的向量", "        // Print transformed vector"),
    ("Vorcyc.Mathematics.LinearAlgebra.LinearEquationSolver 是一个静态类，提供求解线性方程组的方法。",
     "`LinearEquationSolver` is a static class for solving linear systems."),
    ("  - 使用高斯消元法求解线性方程组 Ax = b。", "  - Solves Ax = b with Gaussian elimination."),
    ("    - `A`: 系数矩阵 A。", "    - `A`: Coefficient matrix."),
    ("    - `b`: 常数向量 b。", "    - `b`: Right-hand side vector."),
    ("  - Returns: 解向量 x。", "  - Returns: Solution vector x."),
    ("  - Thrown when 矩阵 A 不是方阵或 A 的行数与向量 b 的维度不匹配时抛出。",
     "  - Thrown when A is not square or dimensions of A and b do not match."),
    ("  - 原地求解 Ax = b，将结果写入 `x`；可选传入 `augmentedWorkspace`（n×(n+1)）以避免重复分配增广矩阵。",
     "  - Solves Ax = b in place into `x`; optional `augmentedWorkspace` (n×(n+1)) avoids reallocating the augmented matrix."),
    ("  - 使用 LU 分解法求解线性方程组 Ax = b。", "  - Solves Ax = b with LU decomposition."),
    ("  - 使用 Jacobi 法求解线性方程组 Ax = b。", "  - Solves Ax = b with the Jacobi method."),
    ("    - `tolerance`: 收敛容差。", "    - `tolerance`: Convergence tolerance."),
    ("  - 使用 Gauss-Seidel 法求解线性方程组 Ax = b。", "  - Solves Ax = b with Gauss–Seidel."),
    ("`public static T[] CholeskySolve<T>(Matrix<T> A, T[] b)` — 对称正定方程组 Ax = b（A = LLᵀ）",
     "`public static T[] CholeskySolve<T>(Matrix<T> A, T[] b)` — symmetric positive definite Ax = b (A = LLᵀ)"),
    ("`SolveLeastSquares<T>(Matrix<T> designMatrix, ReadOnlySpan<T> y)` — min ‖Ax − y‖²；法方程优先，病态时自动 SVD",
     "`SolveLeastSquares<T>(Matrix<T> designMatrix, ReadOnlySpan<T> y)` — min ‖Ax − y‖²; normal equations first, SVD when ill-conditioned"),
    ("`SolveRidgeLeastSquares<T>(Matrix<T> designMatrix, ReadOnlySpan<T> y, T lambda, bool regularizeIntercept = true)` — 岭回归",
     "`SolveRidgeLeastSquares<T>(Matrix<T> designMatrix, ReadOnlySpan<T> y, T lambda, bool regularizeIntercept = true)` — ridge regression"),
    ("`SolveLeastSquaresSvd<T>(Matrix<T> designMatrix, ReadOnlySpan<T> y, T? tolerance = null)` — 薄 SVD 伪逆，适用于秩亏设计矩阵",
     "`SolveLeastSquaresSvd<T>(Matrix<T> designMatrix, ReadOnlySpan<T> y, T? tolerance = null)` — thin SVD pseudoinverse for rank-deficient design matrices"),
    ("        // 使用高斯消元法求解", "        // Gaussian elimination"),
    ("        // 使用 LU 分解法求解", "        // LU decomposition"),
    ("        // 使用 Jacobi 法求解", "        // Jacobi method"),
    ("        // 使用 Gauss-Seidel 法求解", "        // Gauss–Seidel method"),
    ("Vorcyc.Mathematics.LinearAlgebra.Matrix 是一个表示二维矩阵的类，提供了矩阵的基本操作和运算方法。",
     "`Matrix` represents a 2D matrix with basic operations."),
    ("  - Gets 矩阵的行数。", "  - Gets row count."),
    ("  - Gets 矩阵的列数。", "  - Gets column count."),
    ("  - Uses 指定的行数和列数构造一个矩阵。", "  - Constructs a matrix with the given rows and columns."),
    ("    - `rows`: 行数。", "    - `rows`: Row count."),
    ("    - `columns`: 列数。", "    - `columns`: Column count."),
    ("  - Uses 指定的大小构造一个方阵。", "  - Constructs a square matrix of the given size."),
    ("    - `size`: 矩阵的大小（行数和列数）。", "    - `size`: Matrix size (rows and columns)."),
    ("  - Uses 二维数组构造一个矩阵。", "  - Constructs from a 2D array."),
    ("    - `initialValues`: 二维数组形式的初始值。", "    - `initialValues`: Initial values as 2D array."),
    ("  - Gets 或设置指定位置的元素。", "  - Gets or sets the element at the given position."),
    ("    - `row`: 行索引。", "    - `row`: Row index."),
    ("    - `column`: 列索引。", "    - `column`: Column index."),
    ("  - Returns: 指定位置的元素。", "  - Returns: Element at the position."),
    ("#### 1. 隐式转换为二维数组", "#### 1. Implicit conversion to 2D array"),
    ("  - 将矩阵隐式转换为二维数组。", "  - Implicitly converts matrix to 2D array."),
    ("    - `matrix`: 要转换的矩阵。", "    - `matrix`: Matrix to convert."),
    ("#### 2. 隐式转换为锯齿数组", "#### 2. Implicit conversion to jagged array"),
    ("  - 将矩阵隐式转换为锯齿数组。", "  - Implicitly converts matrix to jagged array."),
    ("#### 3. 隐式转换为矩阵", "#### 3. Implicit conversion to matrix"),
    ("  - 将锯齿数组隐式转换为矩阵。", "  - Implicitly converts jagged array to matrix."),
    ("    - `values`: 要转换的锯齿数组。", "    - `values`: Jagged array to convert."),
    ("  - 将二维数组隐式转换为矩阵。", "  - Implicitly converts 2D array to matrix."),
    ("    - `values`: 要转换的二维数组。", "    - `values`: 2D array to convert."),
    ("#### 1. 矩阵加法", "#### 1. Matrix addition"),
    ("  - 矩阵加法运算符。", "  - Matrix addition operator."),
    ("    - `a`: 第一个矩阵。", "    - `a`: First matrix."),
    ("    - `b`: 第二个矩阵。", "    - `b`: Second matrix."),
    ("  - Returns: 两个矩阵的和。", "  - Returns: Sum of matrices."),
    ("#### 2. 矩阵减法", "#### 2. Matrix subtraction"),
    ("  - 矩阵减法运算符。", "  - Matrix subtraction operator."),
    ("  - Returns: 两个矩阵的差。", "  - Returns: Difference of matrices."),
    ("#### 3. 矩阵乘法", "#### 3. Matrix multiplication"),
    ("  - 矩阵乘法运算符。", "  - Matrix multiplication operator."),
    ("  - Returns: 两个矩阵的积。", "  - Returns: Product of matrices."),
    ("#### 4. 矩阵与标量乘法", "#### 4. Matrix–scalar multiplication"),
    ("  - 矩阵与标量乘法运算符。", "  - Matrix–scalar multiplication operator."),
    ("    - `matrix`: 矩阵。", "    - `matrix`: Matrix."),
    ("    - `scalar`: 标量。", "    - `scalar`: Scalar."),
    ("  - Returns: 矩阵与标量的积。", "  - Returns: Product with scalar."),
    ("#### 5. 矩阵与标量除法", "#### 5. Matrix–scalar division"),
    ("  - 矩阵与标量除法运算符。", "  - Matrix–scalar division operator."),
    ("  - Returns: 矩阵与标量的商。", "  - Returns: Quotient with scalar."),
    ("  - Gets 指定行的元素。", "  - Gets elements of the specified row."),
    ("    - `rowIndex`: 行索引。", "    - `rowIndex`: Row index."),
    ("  - Returns: 指定行的元素的 Span。", "  - Returns: `Span` of row elements."),
    ("  - Gets 指定列的元素。", "  - Gets elements of the specified column."),
    ("    - `columnIndex`: 列索引。", "    - `columnIndex`: Column index."),
    ("  - Returns: 指定列的元素的 ReadOnlySpan。", "  - Returns: `ReadOnlySpan` of column elements."),
    ("  - 矩阵转置。", "  - Transposes the matrix."),
    ("  - Returns: 转置后的矩阵。", "  - Returns: Transposed matrix."),
    ("  - Computes 矩阵的行列式。", "  - Computes the determinant."),
    ("  - Returns: 矩阵的行列式。", "  - Returns: Determinant."),
    ("  - Computes 矩阵的逆矩阵。", "  - Computes the matrix inverse."),
    ("  - Returns: 矩阵的逆矩阵。", "  - Returns: Inverse matrix."),
    ("  - LU 分解。", "  - LU decomposition."),
    ("    - `L`: 输出的下三角矩阵。", "    - `L`: Output lower triangular matrix."),
    ("    - `U`: 输出的上三角矩阵。", "    - `U`: Output upper triangular matrix."),
    ("  - QR 分解。", "  - QR decomposition."),
    ("    - `Q`: 输出的正交矩阵。", "    - `Q`: Output orthogonal matrix."),
    ("    - `R`: 输出的上三角矩阵。", "    - `R`: Output upper triangular matrix."),
    ("  - Cholesky 分解。", "  - Cholesky decomposition."),
    ("  - Returns: 下三角矩阵。", "  - Returns: Lower triangular matrix."),
    ("  - 创建一个单位矩阵。", "  - Creates an identity matrix."),
    ("  - Returns: 单位矩阵。", "  - Returns: Identity matrix."),
    ("  - 创建一个伴随矩阵。", "  - Creates a companion matrix."),
    ("    - `a`: 输入数组，表示多项式的系数。", "    - `a`: Polynomial coefficients."),
    ("  - Returns: 伴随矩阵。", "  - Returns: Companion matrix."),
    ("  - Thrown when 输入数组的长度小于 2 或第一个系数为零时抛出。",
     "  - Thrown when coefficient array length < 2 or first coefficient is zero."),
    ("  - 用随机数填充矩阵。", "  - Fills matrix with random values."),
    ("  - 创建矩阵的深拷贝。", "  - Creates a deep copy."),
    ("  - Returns: 矩阵的深拷贝。", "  - Returns: Deep copy."),
    ("  - Returns: 矩阵的字符串表示形式。", "  - Returns: String representation."),
    ("        // 使用二维数组构造矩阵", "        // Construct matrix from 2D array"),
    ("        // 使用行数和列数构造矩阵", "        // Construct matrix by size"),
    ("        // 矩阵加法", "        // Matrix addition"),
    ("        // 矩阵减法", "        // Matrix subtraction"),
    ("        // 矩阵乘法", "        // Matrix multiplication"),
    ("        // 矩阵转置", "        // Transpose"),
    ("        // 计算行列式", "        // Determinant"),
    ("        // 计算逆矩阵", "        // Inverse"),
    ("        // LU 分解", "        // LU decomposition"),
    ("        // QR 分解", "        // QR decomposition"),
    ("        // Cholesky 分解", "        // Cholesky decomposition"),
    ("        // 创建单位矩阵", "        // Identity matrix"),
    ("        // 创建伴随矩阵", "        // Companion matrix"),
    ("        // 矩阵深拷贝", "        // Deep copy"),
    ("Vorcyc.Mathematics.LinearAlgebra.Matrix&lt;T> 是一个表示二维矩阵的泛型类，提供了矩阵的基本操作和运算方法。",
     "`Matrix<T>` is a generic 2D matrix with basic operations."),
    # Experimental Kalman
    ("Vorcyc.Mathematics.Experimental.KalmanFilters.ExtendedKalmanFilter1D&lt;T> 是一个用于一维扩展卡尔曼滤波器的类。",
     "`ExtendedKalmanFilter1D<T>` is a 1D extended Kalman filter."),
    ("  - Initializes 扩展卡尔曼滤波器的实例。", "  - Initializes the extended Kalman filter."),
    ("    - `A`: 状态转移系数。", "    - `A`: State transition coefficient."),
    ("    - `B`: 控制输入系数。", "    - `B`: Control input coefficient."),
    ("    - `H`: 观测系数。", "    - `H`: Observation coefficient."),
    ("    - `Q`: 过程噪声协方差。", "    - `Q`: Process noise covariance."),
    ("    - `R`: 测量噪声协方差。", "    - `R`: Measurement noise covariance."),
    ("    - `initialState`: 初始状态估计。", "    - `initialState`: Initial state estimate."),
    ("    - `initialP`: 初始估计误差协方差。", "    - `initialP`: Initial estimate error covariance."),
    ("  - Performs 预测步骤。", "  - Prediction step."),
    ("    - `u`: 控制输入。", "    - `u`: Control input."),
    ("    - `stateTransitionFunc`: 状态转移函数。", "    - `stateTransitionFunc`: State transition function."),
    ("  - Returns: 预测的状态估计。", "  - Returns: Predicted state."),
    ("  - Performs 更新步骤。", "  - Update step."),
    ("    - `z`: 测量值。", "    - `z`: Measurement."),
    ("    - `measurementFunc`: 观测函数。", "    - `measurementFunc`: Measurement function."),
    ("  - Returns: 更新后的状态估计。", "  - Returns: Updated state."),
    ("        // 定义滤波器参数", "        // Filter parameters"),
    ("        // 创建扩展卡尔曼滤波器实例", "        // Create extended Kalman filter"),
    ("        // 定义非线性状态转移函数", "        // Nonlinear state transition"),
    ("        // 定义非线性观测函数", "        // Nonlinear measurement function"),
    ("        // 定义测量数据", "        // Measurement data"),
    ("        // 执行滤波", "        // Run filter"),
    ("            var u = 0.0f; // 控制输入为0", "            var u = 0.0f; // zero control input"),
    ("            var z = audioSamples[i]; // 当前测量值", "            var z = audioSamples[i]; // current measurement"),
    ("        // 输出滤波结果", "        // Print filtered output"),
    ("Vorcyc.Mathematics.Experimental.KalmanFilters.ExtendedKalmanFilter2D&lt;T> 是一个用于二维扩展卡尔曼滤波器的类。",
     "`ExtendedKalmanFilter2D<T>` is a 2D extended Kalman filter."),
    ("    - `A`: 状态转移矩阵。", "    - `A`: State transition matrix."),
    ("    - `B`: 控制输入矩阵。", "    - `B`: Control input matrix."),
    ("    - `H`: 观测矩阵。", "    - `H`: Observation matrix."),
    ("        // 执行预测步骤", "        // Prediction step"),
    ("        // 执行更新步骤", "        // Update step"),
    ("Vorcyc.Mathematics.Experimental.KalmanFilters.InformationFilter1D&lt;T> 是一个用于一维信息滤波器的类。",
     "`InformationFilter1D<T>` is a 1D information filter."),
    ("  - Initializes 信息滤波器的实例。", "  - Initializes the information filter."),
    ("    - `initialInformationMatrix`: 初始信息矩阵。", "    - `initialInformationMatrix`: Initial information matrix."),
    ("        // 创建信息滤波器实例", "        // Create information filter"),
    ("Vorcyc.Mathematics.Experimental.KalmanFilters.ParticleFilter1D&lt;T> 是一个用于一维粒子滤波器的类。",
     "`ParticleFilter1D<T>` is a 1D particle filter."),
    ("  - Initializes 粒子滤波器的实例。", "  - Initializes the particle filter."),
    ("    - `numParticles`: 粒子数量。", "    - `numParticles`: Number of particles."),
    ("    - `initialStateStdDev`: 初始状态标准差。", "    - `initialStateStdDev`: Initial state standard deviation."),
    ("    - `processNoiseStdDev`: 过程噪声标准差。", "    - `processNoiseStdDev`: Process noise standard deviation."),
    ("    - `measurementNoiseStdDev`: 测量噪声标准差。", "    - `measurementNoiseStdDev`: Measurement noise standard deviation."),
    ("  - Estimates 当前状态。", "  - Estimates current state."),
    ("  - Returns: 当前状态的估计值。", "  - Returns: Current state estimate."),
    ("        // 创建粒子滤波器实例", "        // Create particle filter"),
    ("Vorcyc.Mathematics.Experimental.KalmanFilters.SquareRootKalmanFilter1D&lt;T> 是一个用于一维平方根卡尔曼滤波器的类。",
     "`SquareRootKalmanFilter1D<T>` is a 1D square-root Kalman filter."),
    ("  - Initializes 平方根卡尔曼滤波器的实例。", "  - Initializes the square-root Kalman filter."),
    ("    - `initialS`: 初始协方差平方根。", "    - `initialS`: Initial covariance square root."),
]

# Sort by length descending
PHRASES.sort(key=lambda x: len(x[0]), reverse=True)

LINK_REPLACEMENTS = [
    ("HOME_zh.md", "HOME.md"),
    ("Module_MachineLearning_zh.md", "Module_MachineLearning.md"),
    ("Module_LinearAlgebra_zh.md", "Module_LinearAlgebra.md"),
    ("Module_Experimental_zh.md", "Module_Experimental.md"),
]

ANCHOR_MAP = {
    "类": "class",
    "结构": "struct",
    "接口": "interface",
    "枚举": "enum",
    "模块概览与新增-api": "module-overview-and-new-apis",
    "09-分类器完整示例": "09-classifier-walkthrough",
    "距离度量类": "distance-metric-classes",
}


def translate_headers(text: str) -> str:
    # ## Name 类 -> ## Name class
    text = re.sub(r"^(## .+?) 类\s*$", r"\1 class", text, flags=re.M)
    text = re.sub(r"^(## .+?) 结构\s*$", r"\1 struct", text, flags=re.M)
    text = re.sub(r"^(## .+?) 接口\s*$", r"\1 interface", text, flags=re.M)
    text = re.sub(r"^(## .+?) 枚举\s*$", r"\1 enum", text, flags=re.M)
    # TOC bookmark lines with 类
    text = text.replace("- :bookmark: [", "- :bookmark: [")
    text = re.sub(r"\(#([^)]+)-类\)", lambda m: f"(#{m.group(1)}-class)", text)
    text = re.sub(r"\(#([^)]+)-结构\)", lambda m: f"(#{m.group(1)}-struct)", text)
    text = re.sub(r"\(#([^)]+)-接口\)", lambda m: f"(#{m.group(1)}-interface)", text)
    text = re.sub(r"\(#([^)]+)-枚举\)", lambda m: f"(#{m.group(1)}-enum)", text)
    for zh, en in ANCHOR_MAP.items():
        text = text.replace(f"#{zh}", f"#{en}")
    return text


def translate_file(src: Path, dst: Path) -> int:
    text = src.read_text(encoding="utf-8")
    for old, new in LINK_REPLACEMENTS:
        text = text.replace(old, new)
    for zh, en in PHRASES:
        text = text.replace(zh, en)
    text = translate_headers(text)
    # Generic fallbacks for remaining common patterns
    text = text.replace(" 类", " class")
    text = text.replace(" 结构", " struct")
    text = text.replace(" 接口", " interface")
    text = text.replace(" 枚举", " enum")
    dst.write_text(text, encoding="utf-8", newline="\n")
    return len(text.splitlines())


def main():
    results = []
    for src_name, dst_name, _ in MAPPINGS:
        src = HANS / src_name
        dst = EN / dst_name
        lines = translate_file(src, dst)
        results.append((dst_name, lines))
    for name, lines in results:
        print(f"{name}: {lines} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
